### ISSUE TITLE
St_buffer should have QuadrantSegment / endcap / join / mitreLimit / singleSide input paras 

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#1032]
https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/buffer/BufferParameters.html

I think it's useful for user to use buffer functions like JTS style. 

For example:
https://postgis.net/docs/ST_Buffer.html

**Comment by jiayuasu** [comment]
@MyqueWooMiddo Great idea. I have thought about this but just too busy to do it. Do you want to contribute this logic to Sedona?

**Comment by MyqueWooMiddo** [comment]
> @MyqueWooMiddo Great idea. I have thought about this but just too busy to do it. Do you want to contribute this logic to Sedona?

Maybe it's high risk to do these in Mainland .   Haha!
