### ISSUE TITLE
Zeppelin + Sql + Geometry viewer

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#1067]
It's quite slow to use Zeppelin + Spark Interpreter + Sedona Plugin .
Can I use Zeppelin + Jbdc Interpreter (via Kyuubi) + Sedona plugin to display geometries on Zeppelin notebook?

## Settings

Sedona version = 1.5.0

Apache Spark version = 3.2.2

API type = sql

Scala version = 2.12

JRE version = 1.8

Environment = With Zeppelin

**Comment by MyqueWooMiddo** [comment]
It works with EWKT

**Comment by jiayuasu** [comment]
@MyqueWooMiddo I think you can. The Sedona Zeppelin plugin has nothing to do with the Spark connector. It is just a Javascript library that works for any data sent by the backend.
