### ISSUE TITLE
RS_AsBase64 returns empty string

### ISSUE THREAD

**Issue by chitra-psg** [apache/sedona#1138]
## Expected behavior
Expecting below command  to return string 
SELECT RS_AsBase64(raster) from rasters

## Actual behavior
It returns 1 row 1 column and its empty

## To replicate
geotiff_df = sedona.read.format("binaryFile").load("data/samplefile.tif")
geotiff_df.createOrReplaceTempView("binary_raster")

raster_df = sedona.sql("SELECT RS_FromGeoTiff(content) as raster from binary_raster")
raster_df.createOrReplaceTempView("raster_table")

in SQL,
SELECT RS_AsBase64(raster) from raster_table

## Settings
Sedona version = 1.5.0
Apache Spark version = 3.5.0
API type = SQL
Scala version = 2.12
Environment = Azure Databricks

**Comment by jiayuasu** [comment]
@chitra-psg Would you please share the `samplefile.tif` with us?

**Comment by chitra-psg** [comment]
> @chitra-psg Would you please share the `samplefile.tif` with us?

@jiayuasu please find the file attached
[sample.zip](https://github.com/apache/sedona/files/13646660/sample.zip)

**Comment by furqaankhan** [comment]
Hi @chitra-psg, Thank you for pointing out the issue. Originally we didn't intend to include any floating datatypes to the `RS_AsBase64` function. However, I will add support to floating point datatypes.

I would not recommend that you use `RS_AsBase64` on such a large file. This function should be used only with relatively small files. If you want to visualize it, you may use `RS_AsGeoTiff` and https://sedona.apache.org/1.5.0/tutorial/raster/?h=save+files#save-to-permanent-storage.
