### ISSUE TITLE
Request for addition of function: `ST_LineLocatePoint` 

### ISSUE THREAD

**Issue by jpd-defra** [apache/sedona#1139]
As per request from MoSarwat on the Sedona Discord channel, I'll open this issue.

PostGIS has very useful function called `ST_LineLocatePoint`, which can provide the input value for the `ST_LineInterpolatePoint` function (already found in Sedona). 

I'm wondering if anyone has the expertise to implement this function, as it would be very useful in snapping type workflows.

I'm new to Sedona and wouldn't know how to start with a PR, but happy to try and help if I can. 

The PostGIS docs are [here](https://postgis.net/docs/ST_LineLocatePoint.html).
An example of basic implementation in BigQuery can be found [here](https://www.linkedin.com/pulse/replicating-stlinelocatepoint-function-from-postgis-google-wrigley/).

**Comment by jiayuasu** [comment]
This function can be easily implemented by 

```
    public static double lineLocatePoint(Geometry geom, Geometry point) {
        double length = geom.getLength();
        LengthIndexedLine indexedLine = new LengthIndexedLine(geom);
        return indexedLine.indexOf(point.getCoordinate()) / length;
    }
```

If you are interested, please refer to the implementation of ST_LineInterpolatePoint: https://github.com/apache/sedona/blob/master/common/src/main/java/org/apache/sedona/common/Functions.java#L635

Then create your PR to Sedona

**Comment by jpd-defra** [comment]
Thanks @jiayuasu. Have never written any Java before, but if its just a case of dropping your suggested code into the `Functions.java` file and submitting the PR, then I could do that.

**Comment by jiayuasu** [comment]
@jpd-defra @ojabri1 Hi folks, Sedona 1.5.1 has been released. ST_LineLocatePoint is included! See: https://sedona.apache.org/1.5.1/api/sql/Function/#st_linelocatepoint

Please give it a try!

**Comment by jpd-defra** [comment]
@jiayuasu  - thanks for the heads up. I spun up a Databricks cluster with 1.5.1 but found I was getting a REDACTED_LOCAL_PART type error when trying to read any parquets I had made prior to the upgrade. Not quite sure what is going on, but given a tight deadline for some work, have had to drop back to 1.5.0 for now.
