### ISSUE TITLE
rs_setbandnodatavalue not working as expected

### ISSUE THREAD

**Issue by chitra-psg** [apache/sedona#1148]
## Expected behavior
Expected the band values to be updated with new value provided where it has no data.

## Actual behavior
Trying to sum couple of  raster's 1st band value. Band value is float type and "-3.4028230607370965e+38" is the no data value of the band.
Sum value comes out to -inf since it is summing the no data value.

Tried using rs_setbandnodatavalue to set no data value as 0.0 and then perform sum but cant see the values updated in the band.

df_sedona1 = sedona.read.format("binaryFile").load(vSourcePath1)\
                  .withColumn("raster1", expr("rs_setbandnodatavalue(RS_FromGeoTiff(content),1,0.0)"))\
                  .withColumn("ID", expr("1"))\
                  .withColumn("raster1arr", expr("RS_BandAsArray(raster1,1)"))\
                  .select("ID","raster1", "raster1arr")

...

select RS_Count(raster1,1,True) as cells_withdata
,RS_Count(raster1,1,False) total_cells 
,RS_BandNoDataValue(raster1,1) as nodatavalue
from file1

Before using setnodatavalue
225589 
12325690
 -3.4028230607370965E38

after using setnodatvalue
12325690
12325690
0.0

==> It picked 0.0 as the nodatavalue for the raster but also noticed all cells have been identified as cells with data?
..

band1 = df_sedona1.selectExpr("RS_BandAsArray(raster1, 1)").first()[0]
print(band1[1:50],)
returns array with ""-3.4028230607370965e+38" present it.

==> Didnt expect to see any -3.4028230607370965e+38 in the array values

## Settings
Sedona version = 1.5.0
Apache Spark version = 3.5.0
API type = SQL
Scala version = 2.12
Environment = Azure Databricks

**Comment by jiayuasu** [comment]
@chitra-psg While we are investigating this, can you retry RS_SummaryStats? https://sedona.apache.org/1.5.0/api/sql/Raster-operators/?h=rs_summarystats#rs_summarystats

RS_SummaryStats can return the sum of a band and it also can exclude no data values.

**Comment by jiayuasu** [comment]
@chitra-psg The current behavior of RS_SetBandNoDataValue works as expected. It is not supposed to replace the old values. But we will add a `replace` option to actually replace them. Created a JIRA ticket for it: https://issues.apache.org/jira/browse/SEDONA-448
