### ISSUE TITLE
Installing apache-sedona Python package does not install all dependencies (Sedona 1.5.0)

### ISSUE THREAD

**Issue by jornfranke** [apache/sedona#1151]
## Expected behavior
I use 
```
pip install apache-sedona
```
and all Python dependencies are installed EXCEPT pyspark.

## Actual behavior
Following Python packages are missing:
* keplergl 
* pydeck 

(This you can see when doing from sedona.spark import * - it will complain that they are missing)

When manually installing them it works:
```
pip install keplergl pydeck
```

## Steps to reproduce the problem
see above
## Settings

Sedona version = 1.5.0

Apache Spark version = 3.2.3

Apache Flink version = ?

API type = Python

Scala version = 2.12

JRE version = 1.8

Python version = 3.10

Environment = Standalone, AWS EC2, EMR, Azure, Databricks?

**Comment by jiayuasu** [comment]
@jornfranke Thanks for raising this issue. We noticed this issue in 1.5.0 and have fixed it in https://issues.apache.org/jira/browse/SEDONA-420 . The patch will be in Sedona 1.5.1 which will be out right after the coming New Year!

**Comment by jiayuasu** [comment]
@jornfranke We have released Sedona 1.5.1 and this issue has been fixed :-)
