### ISSUE TITLE
issue about function RS_SetBandNoDataValue

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#1269]
in sedona-1.5.1

RS_SetBandNoDataValue(raster: Raster, bandIndex: Integer, noDataValue: Double, replace: Boolean)

when noDataValue=null  , orginal ndv pixels are still ndv , not replaced by null.

**Comment by jiayuasu** [comment]
@MyqueWooMiddo Currently, the noDataValue in bands cannot be `null`. If you set `noDataValue = null` in the RS_SetBandNoDataValue, the function will omit this param and perform no change.
