### ISSUE TITLE
Unknown user-defined function SEDONASNOW.SEDONA.ST_DUMP

### ISSUE THREAD

**Issue by andreypanchenko** [apache/sedona#1293]
## Expected behavior
[SEDONASNOW.SEDONA.ST_DUMP](https://sedona.apache.org/1.5.1/api/snowflake/vector-data/Function/#st_dump)
I already saw that in the known issue. but for me it's not related to origin of data for this function input
[known-issues](https://sedona.apache.org/1.5.1/tutorial/snowflake/sql/#known-issues)
## Actual behavior

```sql
WITH geom_tbl AS (
    SELECT SEDONASNOW.SEDONA.ST_GeomFromWKT('POLYGON ((-3 -3, 3 -3, 3 3, -3 3, -3 -3))') AS geom
    UNION ALL
    SELECT SEDONASNOW.SEDONA.ST_GeomFromWKT('POLYGON ((-3 -3, 3 -3, 3 3, -3 3, -3 -3))')
    UNION ALL
    SELECT SEDONASNOW.SEDONA.ST_GeomFromWKT('POLYGON ((1 -2, 5 0, 1 2, 1 -2))')
)

SELECT SEDONASNOW.SEDONA.ST_DUMP(geom) dumped_geom
FROM geom_tbl

```

`
[2024-03-26 12:19:36] [42601][2141] SQL compilation error:
[2024-03-26 12:19:36] Unknown user-defined function SEDONASNOW.SEDONA.ST_DUMP
`
![image](https://github.com/apache/sedona/assets/26185177/3dcdfcb2-435d-478e-9568-5869d5648004)
![image](https://github.com/apache/sedona/assets/26185177/663a6d91-0bdb-41c1-bf5b-9a8d743338c8)

## Steps to reproduce the problem
install SNOWSEDONA snowflake application, or import custom .jar files to Snowflake
## Settings

Sedona version = 1.51
Environment = Snowflake

**Comment by jiayuasu** [comment]
@andreypanchenko We should update the doc. The correct usage is https://github.com/apache/sedona/blob/master/snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestTableFunctions.java#L107

```
select count(1) from table(sedona.ST_Dump(sedona.ST_GeomFromText('MULTIPOINT ((10 40), (40 30), (20 20), (30 10))')));
```
