### ISSUE TITLE
Suggested edit to documentation 

### ISSUE THREAD

**Issue by JimShady** [apache/sedona#1314]
https://sedona.apache.org/1.5.1/api/sql/Raster-loader/#rs_makeemptyraster

When making a global raster using, for example, WGS84, the pixel size on the y axis should be specified as a negative number. I think this is a 'gotcha' and should be explicitly explained?

For example:

```
SELECT RS_MakeEmptyRaster(1, -- bands
                          'I', -- datatype
                          360, -- width
                          180, -- height
                          -180, -- upperlefx
                          90, -- upperlefty
                          1, -- scalex (pixel size)
                          **-1, -- scaley (pixel size)**
                          0.0, -- skewx
                          0.0, -- skewy
                          4326) -- srid
```

**Comment by jiayuasu** [comment]
@Kontinuation Do you know why the pixel size on Y (scaleY) can be negative?

**Comment by Kontinuation** [comment]
The pixels with lower Y grid/pixel coordinate is mapped to larger Y value of map coordinate, so a negative scaleY indicates a north-up image, which is the most common case.

`scaley` is actually an element of the affine transformation matrix, it should not be treated as the pixel size. So yes, the documentation is quite misleading.
