### ISSUE TITLE
what can i run it with no network?

### ISSUE THREAD

**Issue by liuhao0826** [apache/sedona#1321]
# sedona_config = SedonaContext.builder(). \
    #     master("local[*]"). \
    #     config("spark.jars", "./spark-doris-connector-3.4_2.12-1.3.0.jar"). \
    #     config('spark.jars.packages',
    #            'org.apache.sedona:sedona-spark-3.4_2.12:1.5.1,'
    #            'org.datasyslab:geotools-wrapper:1.5.1-28.2'). \
    #     config('spark.jars.repositories', 'https://artifacts.unidata.ucar.edu/repository/unidata-all'). \
    #     getOrCreate()

i should to change this startconfig，because my development with no network，so i change this to：
    sedona_config = SedonaContext.builder(). \
        master("local[*]"). \
        config("spark.jars",
               "./spark-doris-connector-3.4_2.12-1.3.0.jar,./sedona-spark-3.4_2.12-1.5.1.jar,"
               "./geotools-wrapper-1.5.1-28.2.jar"). \
        getOrCreate()
but its run to ：org.apache.spark.SparkException: Failed to register classes with Kryo
how to solve it？

**Comment by jiayuasu** [comment]
@liuhao0826 You should use `sedona-spark-shaded-3.4_2.12:1.5.1` since you have no internet

**Comment by liuhao0826** [comment]
with your approach，solved it current，thanks for  you @jiayuasu
