### ISSUE TITLE
Package Conflict when I use ST_AsGeoJSON

### ISSUE THREAD

**Issue by liuhao0826** [apache/sedona#1341]
Sedona version = 1.5.1
Apache Spark version = 3.4.2
API type =  Python
Scala version = 2.12
JRE version = 1.8
Python version = 3.9.13
Environment = Standalone,

    sedona_config = SedonaContext.builder(). \
        master("local"). \
        appName("ag_count_hour_ods_df_app"). \
        config("spark.driver.memory", "20G"). \
        config("spark.jars",
               "./spark-doris-connector-3.4_2.12-1.3.0.jar,./sedona-spark-shaded-3.4_2.12-1.5.1.jar,"
               "./geotools-wrapper-1.5.1-28.2.jar"). \
        getOrCreate()
    final_df = segments_df.selectExpr("ST_AsGeoJSON(ST_ConvexHull(ST_GeomFromText(polygon_text))) as polygon_geojson")
   

issued with：image
![1713254426664](https://github.com/apache/sedona/assets/65433251/b263466c-71ef-481a-8401-e24131e319c8)

how to solve it?

**Comment by jiayuasu** [comment]
@liuhao0826 This is really strange. Did you by any chance put some sedona jars in SPARK_HOME/jars?

**Comment by liuhao0826** [comment]
> @liuhao0826 This is really strange. Did you by any chance put some sedona jars in SPARK_HOME/jars?

Thank you, I remember ten days ago when I threw the geospark related jar package into the jars directory and forgot to remove it
