### ISSUE TITLE
AWS Glue official tutorial

### ISSUE THREAD

**Issue by hongbo-miao** [apache/sedona#1399]
It would be great to add an official tutorial for AWS Glue,  thanks! 😃

![image](https://github.com/apache/sedona/assets/3375461/be15d1f6-a381-47f3-922a-522d87ceb97d)

Here has some info which could help:

https://repost.aws/questions/QUlsAQpbPqTwK_Fn1-6UFkpA/aws-glue-job-notebook-access-to-spark-package-apache-sedona-etc

**Comment by jiayuasu** [comment]
@hongbo-miao were you able to make Sedona work in Glue? I did try it before but wasn't able to do it...

**Comment by hongbo-miao** [comment]
I haven't tried, but I do need give a try soon. If I succeed first, I will report back!

**Comment by hongbo-miao** [comment]
@jiayuasu I haven't tried, but I do need give a try soon. If I succeed first, I will report back!

**Comment by james-willis** [comment]
I've done this before. I will write up a tutorial in the next few weeks.

**Comment by jiayuasu** [comment]
A preview of the Glue doc is here: https://sedona.apache.org/latest-snapshot/setup/glue/

Closing the issue now

**Comment by hongbo-miao** [comment]
Thank you so much, @james-willis ! 🥳
