### ISSUE TITLE
after latest update of sedona snow on snowflake side all functions are gone

### ISSUE THREAD

**Issue by andreypanchenko** [apache/sedona#1407]
## Expected behavior
after installing of Sedona Snow app from Snowflake app store I expect to find all the functions in Apache Sedona application
## Actual behavior
after 2 days ago updates on the snowflake side (background app updates from app provider side) all functions were gone and our production was broken
![image](https://github.com/apache/sedona/assets/26185177/5e943149-ccd9-489f-9dac-4cbf7376c260)

## Steps to reproduce the problem
install apache Sedona from snowflake
## Settings
![image](https://github.com/apache/sedona/assets/26185177/9b28933d-7bcb-41b3-bab4-ad5f0fd59bd8)

Sedona version = 1.5.1.4  or 1.5.2
Environment = Snowflake

**Comment by jiayuasu** [comment]
@andreypanchenko For some unknown reasons, the upgrade does not include any function. I am still investigating. However, I have reverted the SedonaSnow package to 1.5.1. If you uninstall and install the package again manually, the functions will be back.

**Comment by andreypanchenko** [comment]
Following your recommendatons.

still nothing.

![image](https://github.com/apache/sedona/assets/26185177/9b2f74f5-3aa0-43d3-b39e-419aa9f1b45f)

**Comment by jiayuasu** [comment]
This has been fixed in SedonaSnow 1.6.0 released, about 2 months ago
