### ISSUE TITLE
datatype geometry is not supported when 'create table xxx (geom geometry)'

### ISSUE THREAD

**Issue by freamdx** [apache/sedona#1414]
## Expected behavior
![image](https://github.com/apache/sedona/assets/33746390/a41092d1-30e3-42fe-a75c-a82c29d09420)

## Actual behavior
![image](https://github.com/apache/sedona/assets/33746390/1ca3e29d-e01c-4909-8cf8-753320109e95)

## Steps to reproduce the problem
1. server: copy sedona-spark-shaded-3.x_2.12-1.5.x.jar to 'spark/jars'
2. client: connect to spark-thrift-server,  eg: beeline -u jdbc:hive2://<...>:<...>
3. client: create table test (geom geometry);

## Settings

Sedona version = 1.5

Apache Spark version = 3.x

Environment = spark-thrift-server

**Comment by freamdx** [comment]
one way (not best):
![image](https://github.com/apache/sedona/assets/33746390/8765d088-d830-49f8-b353-6f2e1b479f6d)

**Comment by freamdx** [comment]
refer: https://github.com/freamdx/spark/commit/cf2b0fe18c938744f2cfb111f6878eec8ad220cf

**Comment by jiayuasu** [comment]
@freamdx Thanks. This is on our radar. This can be done via adding a custom Sedona SQL parser on top of Spark, without forking Spark code. We will add the support in 1.6.1 release.

**Comment by zhangfengcdt** [comment]
@freamdx The issue is currently being worked on. Before the fix, I think you can use the following workaround to create the Hive table.
```
CREATE OR REPLACE TEMP VIEW EMPTY_VIEW AS
SELECT ST_GEOMFROMTEXT(CAST(NULL AS STRING)) AS GEOM
WHERE 1 = 0;

CREATE TABLE T_TEST AS (SELECT * FROM EMPTY_VIEW);

```
