### ISSUE TITLE
St_isempty(geometry) finds non null geometries but does not find null geometries.

### ISSUE THREAD

**Issue by robertnagy1** [apache/sedona#1427]
## Expected behavior
I have a geopackage with 3800 rows, and about half of them contain null geometries. (It is vendor data so i cannot share freely)
When i run df.where("St_isempty(geometry)==False").count() i get about half of the geometries that do not contain null. 
When i run df.where("St_isempty(geometry)==True").count() i should get about half of the geometries that  contain null. 

## Actual behavior

When i run df.where("St_isempty(geometry)==True").count() i get 0 geometries that contain Null even though i have nulls in my geometry column.
![image](https://github.com/apache/sedona/assets/134613492/752a62e7-c07d-4844-a88c-775fbde8074b)
## Settings

Sedona version = 1.5.1

Apache Spark version = 3.4

Apache Flink version = ?

API type = Python

Scala version =  2.12

JRE version =

Python version = 

Environment = Fabric

**Comment by Kontinuation** [comment]
The expression `ST_IsEmpty(NULL)` will evaluate to `NULL`. Since SQL uses three-valued logic, where TRUE, FALSE, and NULL are distinct values, you may need to use the following query to find NULL or empty geometries:

```python
df.where("geometry IS NULL OR ST_IsEmpty(geometry)").count()
```

**Comment by robertnagy1** [comment]
Thank you. It wasn't clear to me if the cell gets evaluated as being empty, or the content gets evaluated as being empty. :)
