### ISSUE TITLE
ST_Snap example code does not work

### ISSUE THREAD

**Issue by s-flint-defra** [apache/sedona#1438]
## Expected behavior
For this sql example to work https://sedona.apache.org/1.5.1/api/sql/Function/?h=st_snap#st_snap

**%sql
SELECT ST_Snap(
        ST_GeomFromWKT('POLYGON ((236877.58 -6.61, 236878.29 -8.35, 236879.98 -8.33, 236879.72 -7.63, 236880.35 -6.62, 236877.58 -6.61), (236878.45 -7.01, 236878.43 -7.52, 236879.29 -7.50, 236878.63 -7.22, 236878.76 -6.89, 236878.45 -7.01))') as poly,
        ST_GeomFromWKT('LINESTRING (236880.53 -8.22, 236881.15 -7.68, 236880.69 -6.81)') as line,
       ST_Distance(poly, line) * 1.01
       )**

## Actual behavior
Syntax error in or around 'as'

## Working example
**%sql
SELECT
  ST_Snap(line, poly, ST_Distance(poly, line) * 1.01) AS linesnapped
FROM
  (
    SELECT
      ST_GeomFromWKT(
        'POLYGON ((236877.58 -6.61, 236878.29 -8.35, 236879.98 -8.33, 236879.72 -7.63, 236880.35 -6.62, 236877.58 -6.61), (236878.45 -7.01, 236878.43 -7.52, 236879.29 -7.50, 236878.63 -7.22, 236878.76 -6.89, 236878.45 -7.01))'
      ) as poly,
      ST_GeomFromWKT(
        'LINESTRING (236880.53 -8.22, 236881.15 -7.68, 236880.69 -6.81)'
      ) as line
  )**

## Steps to reproduce the problem
Running the example code

## Settings

Sedona version = 1.6.0

Apache Spark version = 3.4.1

API type = SQL

Scala version = 2.12

Python version = 3.10.12

Environment = Azure Databricks

**Comment by furqaankhan** [comment]
Thank you for pointing out the documentation issue. I have created a PR to address this.

**Comment by s-flint-defra** [comment]
No problem - thanks :)
