### ISSUE TITLE
PointRDD Streaming

### ISSUE THREAD

**Issue by SiefSeif** [apache/sedona#148]
My use case is a large stream of Points, how could I achieve streaming into PointRDD and process data like Spark Streaming?, I have to process all in memory without writing into files. Thank you.

**Comment by jiayuasu** [comment]
Hi @SiefSeif ,

To be honest, we haven't tried it yet. But we have received a user report that says they can use it in Spark Streaming.

Thanks,
Jia

**Comment by SiefSeif** [comment]
That's great, could you please send me the report if it's possible? Or a contact for the reporters...thank you.

**Comment by jiayuasu** [comment]
See the conversion in https://gitter.im/geospark-datasys/Lobby on March 01 2017

**Comment by jiayuasu** [comment]
Noticed that @SiefSeif uploaded an interesting document about how to use GeoSpark in Spark Streaming.

https://github.com/SiefSeif/GeoSpark/blob/patch-1/Using%20GeoSpark%20with%20Spark%20Streaming.md
