### ISSUE TITLE
Add Azure Blob Storage support for GeoSparkViz

### ISSUE THREAD

**Issue by jiayuasu** [apache/sedona#151]
GeoSpark viz is able to persist images onto local disk, HDFS and Amazon S3. Here we want to add the support of another popular cloud storage service Microsoft Azure Blob Storage.

My thinking is to use Azure Java SDK and call it in GeoSpark Viz to manipulate images.

**Comment by zhouning** [comment]
Can also support local S3-Compatible API?

**Comment by jiayuasu** [comment]
@zhouning AWS S3 is supported by GeoSparkViz. Please read the JavaDoc here: http://www.public.asu.edu/~jiayu2/geosparkviz/javadoc/1.1.0/org/datasyslab/geosparkviz/extension/imageGenerator/GeoSparkVizImageGenerator.html

**Comment by hucaser** [comment]
Maybe I can try to solve this problem.

**Comment by jiayuasu** [comment]
@hucaser Thanks a lot! Please go ahead and implement this. You can refer to GeoSparkViz S3 operator and write a similar function for Azure.

**Comment by hucaser** [comment]
What I need to do is implement some functions like "SaveRasterImageAsS3File" ? Such as, SaveRasterImageAsAzureBlobFile?

**Comment by jiayuasu** [comment]
@hucaser Yes, you are right!

**Comment by hucaser** [comment]
After several days investigation, I find that storing data into Azure Blob Storage requires an Azure account. I would like to confirm several things with you.

First: I need to register an Azure account.
Second: I use this account in the code, and store data to Azure.
Third: save each image on Azure, and the file path is "outputPath + . + imageType"

Am I right?

**Comment by jiayuasu** [comment]
@hucaser , yes, you are right. But remember that, don't put ANY account information in the code. This means you need to design a proper function API to take the credentials from the user and given these credentials, the function can find the storage bucket and get the permission to write the data.

For example, in Amazon S3, you can get the permission to write data to a specific S3 bucket using 
```
String accessKey, String secretKey
```

I guess there will be a similar solution provided by Azure.

Again, thanks for taking time to solve this issue.
