### ISSUE TITLE
1.6.0 documentation needs update?

### ISSUE THREAD

**Issue by JimShady** [apache/sedona#1513]
Running the commands here:

https://sedona.apache.org/1.6.0/setup/databricks/#initialize

```
from sedona.register.geo_registrator import SedonaRegistrator
SedonaRegistrator.registerAll(spark)
```

Gives the message:

```
/root/.ipykernel/1693/command-801172697299958-79051556:2: DeprecationWarning: Call to deprecated function registerAll (Deprecated since 1.4.1, use SedonaContext.create() instead.).
  SedonaRegistrator.registerAll(spark)
```

I guess that the documentation needs updating?

**Comment by jiayuasu** [comment]
You are right. The latest usage is here: https://sedona.apache.org/1.6.0/tutorial/sql/#initiate-sedonacontext

**Comment by JimShady** [comment]
Thanks.

**Comment by JimShady** [comment]
Though running on Databricks, I now get this error:

    NameError: name 'config' is not defined

I guess I need to do something to create config before.

**Comment by JimShady** [comment]
Ah it looks like I can just replace 'config' with 'spark' like this.

```
from sedona.spark import *
sedona = SedonaContext.create(spark)
```

**Comment by jiayuasu** [comment]
Yes, all you need is 

```
from sedona.spark import *
sedona = SedonaContext.create(spark)
```

**Comment by JimShady** [comment]
Thanks
