### ISSUE TITLE
Wrong link for AWS glue setup docs

### ISSUE THREAD

**Issue by aitor94** [apache/sedona#1683]
The link in glue setup docs for sedona 1.6.1 is wrong:
https://sedona.apache.org/latest/setup/glue/

It's the first link for jar file in Sedona Jar bullet.

![image](https://github.com/user-attachments/assets/3368d467-e9b5-4075-9464-18e38337e5eb)

Sedona version = 1.6.1

Apache Spark version = 3.3

Scala version = 2.12

Environment = Glue

**Comment by jiayuasu** [comment]
@aitor94 sorry, why is it wrong? I didn't get it.

**Comment by james-willis** [comment]
I think we should close this as a duplicate of https://github.com/apache/sedona/issues/1685

**Comment by aitor94** [comment]
@jiayuasu The link was pointing to shaded jar in version 3.3. Now points to version 3.0. Fixed.

Thanks!!
