### ISSUE TITLE
Issue on the documentation steps on how to configure Sedona in AWS Glue using a pyspark ETL job

### ISSUE THREAD

**Issue by MDiakhate12** [apache/sedona#1685]
## Expected behavior
I want to use Apache Sedona in pyspark in an AWS glue environment.

## Actual behavior
The sedona librarie does not work when following the steps described in the doc : https://sedona.apache.org/latest-snapshot/setup/glue/

Error sent : 

```python
Traceback (most recent call last):
  File "/path/to/my/file.py", line 23, in <module>
    sedona = SedonaContext.create(spark)
  File "/home/glue_user/.local/lib/python3.10/site-packages/sedona/spark/SedonaContext.py", line 38, in create
    spark._jvm.SedonaContext.create(spark._jsparkSession, "python")
TypeError: 'JavaPackage' object is not callable
```

Error happens in line `sedona = SedonaContext.create(spark)`

```python
# -*- coding: utf-8 -*-
import sys
from awsglue.context import GlueContext
from awsglue.job import Job
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from sedona.spark import SedonaContext

# JOB CONTEXT SETUP
args = getResolvedOptions(sys.argv, ["JOB_NAME", "environment", "additional-python-modules", "extra-jars", "extra-py-files"])

print(args)

# Method 1
glue_context = GlueContext(SparkContext())

spark = glue_context.spark_session

job = Job(glue_context)

sedona = SedonaContext.create(spark)

print(SedonaContext)
print(sedona)
```

It seems that apache-sedona is not able to find the jar file.

## Steps to reproduce the problem

Create a pyspark ETL Job on AWS Glue web console :

1. Go to AWS Glue > Data Integration and ETL > ETL Jobs 
2. Click on Create job > Script editor > Engine = Spark
3. Documentation steps:
  .  From your job's page, navigate to the "Job details" tab. At the bottom of the page expand the "Advanced properties" section. In the "Dependent JARs path" field, add the paths to the jars, separated by a comma (it corresponds to versions **[sedona-spark-shaded-3.3_2.12/1.6.1/sedona-spark-shaded-3.3_2.12-1.6.1.jar](https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.3_2.12/1.6.1/sedona-spark-shaded-3.3_2.12-1.6.1.jar)** and **[geotools-wrapper-1.6.1-28.2.jar](https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.6.1-28.2/geotools-wrapper-1.6.1-28.2.jar)**)
  .  Add the Sedona Python package by navigating to the "Job Parameters" section and add a new parameter with the key --additional-python-modules and the value apache-sedona==1.6.1
5. Use the code show above
6. Click Save and Run

You can repeat the same step using aws glue locally in docker by following [this official documentation on AWS](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html#develop-local-docker-image-setup-visual-studio)

and then run your script inside the container using :

```bash
/usr/local/bin/python3 "$PYTHON_SCRIPT" \
    --JOB_NAME "$JOB_NAME" \
    --environment "$ENVIRONMENT" \
    --enable-glue-datacatalog \
    --extra-jars https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.3_2.12/1.6.1/sedona-spark-shaded-3.3_2.12-1.6.1.jar, https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.6.1-28.2/geotools-wrapper-1.6.1-28.2.jar \
    --additional-python-modules apache-sedona==1.6.1 \
    --job-language python
```

## Settings

Sedona version = 1.6.1

Apache Spark version = 3.3.0

Apache Flink version = ?

API type = Python

Scala version = 2.12

Python version = 3.12

Environment = AWS Glue

**Comment by james-willis** [comment]
Look like the maven link for sedona is incorrect in the docs. We'll need to raise a PR to revise that.

I actually dont see a 3.3 version on maven: https://central.sonatype.com/search?q=sedona-spark-shaded-3.3

@jiayuasu do we need to use the 3.0 version?

**Comment by jiayuasu** [comment]
@james-willis @MDiakhate12 The URL is for the latest-snapshot of Sedona which is about an unreleased version. Please use the `latest` or `1.6.1` version of Sedona website and the url there will work: https://sedona.apache.org/1.6.1/setup/glue/

**Comment by james-willis** [comment]
Jia, the 1.6.1 link OP provides in step 3 of the repro is dead as well.

**Comment by MarekAntonius** [comment]
Hi, I came across the same issue as MDiakhate12 described. I'm using 
Spark 3.4
Python 3.10
Sedona 1.6.1
Shapely 2.0.6
Scala 2.12
and running on AWS EMR.

The solution didn't work for me. The same error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File <path-to-file>, line 38, in create
    spark._jvm.SedonaContext.create(spark._jsparkSession, "python")
TypeError: 'JavaPackage' object is not callable

**Comment by jiayuasu** [comment]
@MarekAntonius which Sedona jar are you using? If you use Spark 3.4, you should use `sedona-spark-shaded-3.4_2.12-1.6.1.jar`. The OP is on AWS Glue. The tutorial for EMR is here: https://sedona.apache.org/1.6.1/setup/emr/

**Comment by MDiakhate12** [comment]
> Look like the maven link for sedona is incorrect in the docs. We'll need to raise a PR to revise that.
> 
> I actually dont see a 3.3 version on maven: https://central.sonatype.com/search?q=sedona-spark-shaded-3.3
> 
> @jiayuasu do we need to use the 3.0 version?

Hi,

Thank you for your responses. 

In fact, we did not found the version of sedona that matches our spark 3.3 in the listed jars.
We are actually using the latest version of the website now too
Our Environment : 
* Glue 4.0
* Python 3.12
* Spark 3.3.0
* apache-sedona==1.6.1 (python package)
* jar: geotools-wrapper-1.6.1-28.2.jar
* jar: sedona-spark-shaded-3.0_2.12-1.6.1.jar
* Java 8

**Comment by jiayuasu** [comment]
@MDiakhate12 

Note that: In Sedona 1.6.1 and before, we use `sedona-spark-shaded-3.0_2.12-1.6.1.jar` for all spark 3.0 - 3.3 so there is no `3.3` version of jar. This is expected. (However, this will be changed in the upcoming release.)

If you follow this tutorial (https://sedona.apache.org/1.6.1/setup/glue/), it should work. Pay attention to the `1.6.1` in the URL.

**Comment by MDiakhate12** [comment]
Hi Jia,

Thank you for you response

It might be caused by a compatibilty issue somewhere ?

I'm clearly using :
[https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.0_2.12/1.6.1/sedona-spark-shaded-3.0_2.12-1.6.1.jar](https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.0_2.12/1.6.1/sedona-spark-shaded-3.0_2.12-1.6.1.jar)

[https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.6.1-28.2/geotools-wrapper-1.6.1-28.2.jar](https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.6.1-28.2/geotools-wrapper-1.6.1-28.2.jar)

using the correct link [https://sedona.apache.org/1.6.1/setup/glue/](https://sedona.apache.org/1.6.1/setup/glue/) and having the same issue.

We had make sure there is no connectivity issue while getting the jars from Glue. 

But we're still having the  same issue with the versions mentionned

Here are some screenshots from Glue :

`glue error`
![image](https://github.com/user-attachments/assets/ce96ae47-fdd8-41dc-9b44-a603fdcd6e93)

`glue depent jars configuration`
![image](https://github.com/user-attachments/assets/16b10b0a-0ee0-412f-a690-ca33b84bb9af)

**Comment by Kontinuation** [comment]
I read from the screenshot that you are using the jars compiled for Scala 2.13 (sedona-spark-shaded-3.0_**2.13**). The most commonly used spark distributions requires Scala 2.12 so this could be a problem. Have you tried specifying the `sedona-spark-shaded-3.0_2.12-1.6.1.jar` in glue depent jars configuration?

**Comment by MDiakhate12** [comment]
It finally worked with this combination 

`https://repo1.maven.org/maven2/org/apache/sedona/sedona-spark-shaded-3.0_2.12/1.6.1/sedona-spark-shaded-3.0_2.12-1.6.1.jar`

`https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.6.1-28.2/geotools-wrapper-1.6.1-28.2.jar`

We made sure we use the link with repo1.maven.org domain name instead of repo.maven.apache.org

Thank you all for your contributions 😊
