### ISSUE TITLE
APache-sedona Failure

### ISSUE THREAD

**Issue by tony189** [apache/sedona#1688]
Installing JAR libraries from initScript and then apache-sedona 1.6.0 or 1.6.1 makes imposible to execute any notebook. throwing the error

Failure starting repl. Try detaching and re-attaching the notebook.

	at com.databricks.spark.chauffeur.ExecContextState.processInternalMessage(ExecContextState.scala:347)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

Doesn't matther if reattach, create new notebook ,or restart... always fails. Without  apache-sedona everything works
## Settings

Sedona version = sedona-spark-shaded-3.4_2.12-1.6.1.jar geotools-wrapper-1.6.1-28.2.jar

Apache Spark version = 3.5.0

Environment = Azure, Databricks

**Comment by tony189** [comment]
I didn't realize what you point @jiayuasu, I changed it but still didn't wok.

Installing numpy and pandas as @Kontinuation said, fix the problem... even though both libraries are included in every databricks cluster as a standard config with those exact conditions.... 

However in this way the cluster takes ages to start... I think I'm gona stuck with the sql and forget about python.

**Comment by jiayuasu** [comment]
@Kontinuation It think it might be best if we remove `rasterio` from the mandatory dependency of Sedona 1.7.0?

**Comment by Kontinuation** [comment]
> @Kontinuation It think it might be the best if we remove `rasterio` from the mandatory dependency of Sedona 1.7.0?

Good point. There are many other rasterio related issues reported by users because it is hard to get rasterio and GDAL installed on some particular environments.
