### ISSUE TITLE
pre-commit hooks no longer self contained: requires local system dependency on executable `Rscript`

### ISSUE THREAD

**Issue by jbampton** [apache/sedona#1719]
refs https://github.com/apache/sedona/pull/1717

```
sedona$ make check
pre-commit run --all-files
[INFO] Installing environment for https://github.com/lorenzwalthert/precommit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('Rscript', '--vanilla', '/tmp/tmpsowm04ew/script.R')
return code: 1
stdout:
    Executable `Rscript` not found
stderr: (none)
Check the log at /home/abe/.cache/pre-commit/pre-commit.log
make: *** [Makefile:19: check] Error 3
```

https://pre-commit.com/#r

"Support: r hooks work as long as [R](https://www.r-project.org/) is installed and on PATH. It has been tested on linux, macOS, and windows."

**Comment by jiayuasu** [comment]
OK. I guess we might want to revert this commit? @gregleleu

**Comment by gregleleu** [comment]
I'm a bit confused why it works on the Github Action machine, where we never specifically install R. But ok to revert and drop the idea of pre-commit for R

**Comment by jbampton** [comment]
We have R software already so I think we can keep this and just reference in our docs the requirement.

https://sedona.apache.org/latest/setup/compile/#pre-commit

**Comment by gregleleu** [comment]
Feels like a big requirement and that's not going to be relevant to the majority. Also don't want to force people to add a long SKIP variable for each commit (it's multiple hooks)

**Comment by jbampton** [comment]
> I'm a bit confused why it works on the Github Action machine, where we never specifically install R. But ok to revert and drop the idea of pre-commit for R

Under Set up Job -> Runner Image says `ubuntu-22.04`:

https://github.com/apache/sedona/actions/runs/12265615546/job/34222167235

![Screenshot from 2024-12-13 01-30-44](https://github.com/user-attachments/assets/3ffc8610-4690-4e8b-8e29-14579c405cb5)

Links to the image readme and under tools heading has `R 4.4.2` installed.

https://github.com/actions/runner-images/blob/ubuntu22/20241201.1/images/ubuntu/Ubuntu2204-Readme.md#tools
