### ISSUE TITLE
KNN function for Spark SQL

### ISSUE THREAD

**Issue by alifiyaali** [apache/sedona#180]
Nearest Neighbor Search implementation is missing for Spark SQL. A join function should be available where one column of DataFrame A is considered as input for which neighbor will be searched in other DataFrame B.

**Comment by jiayuasu** [comment]
@alifiyaali KNN join function is still missing in GeoSpark. If you are interested in KNN function only, try the following:

1. for GeoSpark RDD API:
Use KnnQuery.SpatialKNNQuery()

2. for GeoSpark SQL API:
Use the following format
```
SELECT polygondf.countyshape, ST_Distance(polygondf.countyshape, ST_Point(1.0,1.0)) as distance
FROM polygondf
ORDER BY distance
LIMIT 5
```
