### ISSUE TITLE
[Call For Contribution] Implement complete SQL/MM and PostGIS functions in GeoSparkSQL

### ISSUE THREAD

**Issue by jiayuasu** [apache/sedona#200]
We have implemented some SQL/MM-Part 3 functions in GeoSparkSQL. But, we need to keep adding more functions into GeoSparkSQL. We will finish these functions in batches based on their importance.

We use PostGIS function references as our  target list: [PostGIS functions](https://postgis.net/docs/reference.html).
Note that, PostGIS function are not 100% SQL/MM Part 3 compatible. When a conflict occurs, use SQL/MM - Part 3 as the golden rules: [SQL/MM Part 3](http://jtc1sc32.org/doc/N1101-1150/32N1107-WD13249-3--spatial.pdf).

GeoSpark users, you are more than welcome to contribute your code to GeoSparkSQL.

**Comment by sumitdvlp** [comment]
Hi,

I want to work on this issue.

**Comment by geoHeil** [comment]
See gitter Chat

@jiayuasu @sumitdvlp would you all be interested in re-using/leveraging
what we already have in GeoMesa?
this sub-module depends only on JTS and Spark and implements most of the
UDFs are you looking for:
https://github.com/locationtech/geomesa/tree/master/geomesa-spark/geomesa-spark-jts

Maybe collaboration is interesting
Sumit Kumar <notifications@github.com> schrieb am Fr. 29. Juni 2018 um
21:42:

**Comment by mikhtonyuk** [comment]
Hi, I'm curious what's the state of this issue. Was there any analysis done or conclusion reached on the possibility of reusing `geomesa-spark-jts` in GeoSpark?

The set of geometry UDFs in GeoSpark is currently very limited and I'd like to help expand it, but the idea of re-implementing all PostGIS functions from scratch seems very counterproductive and will most likely lead to the explosion of bugs and maintenance effort.

**Comment by geoHeil** [comment]
See https://github.com/geoHeil/geomesa-geospark

**Comment by geoHeil** [comment]
It works just fine.  Unfortunately the serialize is different for both projects
