### ISSUE TITLE
GeoSpark Kryo Registrator Issue, why "org.datasyslab.geospark.serde.GeoSparkKryoRegistrator Registering custom serializers for geometry types org.datasyslab.geospark.serde.GeoSparkKryoRegistrator.registerClasses(GeoSparkKryoRegistrator.java:26)" this msg showing many times

### ISSUE THREAD

**Issue by jainisking** [apache/sedona#237]
## Settings

GeoSpark version = ?

Apache Spark version = ?

JRE version = 1.8?

API type = Scala or Java?

**Comment by jainisking** [comment]
I am using java 1.8, GeoSpark version is 1.1.2 and GeoSpark-sql version is

**Comment by jainisking** [comment]
As I am viewing logs,  The msg "Registering custom serializers for geometry types" is showing thousands of times. This may be registering many times for every task. so I am facing the issue of memory, please help.

**Comment by jiayuasu** [comment]
@jainisking This is not a bug. Simply change Log4J setting in your code will disable the log. Add the following line at the beginning of your code.

```
  Logger.getLogger("org.datasyslab").setLevel(Level.WARN)
```

**Comment by alifiyaali** [comment]
@jiayuasu I am facing a similar phenomenon. Setting the logger level to WARN will only prevent INFO logging.
The question is that, if `GeoSparkSQLRegistrator.registerAll(SQLContext arg)` is called once then why is the registration logged for each partition? Does GeoSpark registers functions repeatedly?
