### ISSUE TITLE
join optimization

### ISSUE THREAD

**Issue by geoHeil** [apache/sedona#242]
A common tip to improve the spatial join for postGIS is to use:

```
SELECT 
  a.id, b.id,
  CASE 
    WHEN ST_Contains(a.geom, b.geom)
    THEN b.geom
    ELSE ST_Intersection(a.geom, b.geom)
  END AS geom
FROM a, b
WHERE ST_Intersects(a.geom, b.geom);
```
instead of a naive intersection.
This could also be helpful for geostark / maybe directly integrated into the join?

**Comment by jiayuasu** [comment]
@geoHeil Thanks. Will figure out a way to include this trick in spatial join.

A more detailed description of PostGIS ST_Intersection trick is here: https://postgis.net/2014/03/14/tip_intersection_faster/

**Comment by avshRepo** [comment]
@jiayuasu hi you close this issue becasue i have already enhanced it in the following pull request #301

**Comment by jiayuasu** [comment]
@avshRepo Hi Avsh, please note that this optimization is for join and needs override Spark logical plan "rules" to perform query rewrite. What you did is for the comparison between two objects.
