### ISSUE TITLE
Loading a directory of shapefiles to a ShapefileRDD not supported?

### ISSUE THREAD

**Issue by chadwilcomb** [apache/sedona#243]
## Expected behavior
In the ShapefileRDD constructor I pass in an HDFS directory that contains many shapefiles. I would expect that each of the shapefiles in the directory is read into the ShapefileRDD and the count should reflect the union of each shapefile in the directory.

## Actual behavior
The count returned by shapefileRDD.getShapeRDD().collect().size() corresponds to one of the shapefiles in the directory (not the first or last file either, btw). 

## Steps to reproduce the problem
```
val shapefileRDD = new ShapefileRDD(sc, "/path/with/multiple/shapefiles")
shapefileRDD.getShapeRDD().collect().size()
```

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.1.0

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
Hi @chadwilcomb ,

Loading a directory of shapefiles is not supported. Each folder, namely "myshapefile", should only contain the sub-files of myshapefile. Please see [GeoSpark Doc, reading from shapefile](http://datasystemslab.github.io/GeoSpark/tutorial/rdd/#from-shapefile)

Thanks,
Jia

**Comment by chadwilcomb** [comment]
Thanks for your reply @jiayuasu, and thank you for all your work on this project!

I would argue that this is not the expected behavior from a Spark user's perspective, and it would be a nice feature to have the ability to consume an entire directory of shapefiles.

With the current implementation, it is not even possible to loop through a directory of shapefiles and load them to an RDD, since you need each .shp file (and associated files) to exist within its own directory, correct?

**Comment by jiayuasu** [comment]
@chadwilcomb Understood. Back then, I thought each Shapefile may have its own schema so loading many shapefiles directly into one RDD is not necessary.

However, with the current implementation, you still able to union many shapefile RDDs together using Spark RDD union API. But, still, I agree, this is not a scalable way to solve the problem.

I will try to find a way to iterate all shapefiles in a given folder.

**Comment by chadwilcomb** [comment]
Thanks @jiayuasu! I think this will be super useful. There's not currently a perfect spark solution for our shapefile problem. We use Magellan to ingest our shapefile point datasets, but it is not a good solution for our polygon shapefiles due to the fact there is no simple way to map Magellan polygons to JTS Geometry, which is what we ultimately need. For now we use ogr2ogr in a batch script to convert to GeoJSON first then load with spark json reader.

Thanks again for your efforts on this project!

**Comment by jiayuasu** [comment]
@chadwilcomb I agree with you. Will fix this later. Currently, WKT format is perfectly supported by GeoSpark (either in batches or a single file). Probably you can consider it. GeoJSON is supported as well but not that perfect. 

WKT format (columns must be separated by tabs):
```
POLYGON (..., ...)  Cuming County   
POLYGON (..., ...)  Wahkiakum County
POLYGON (..., ...)  De Baca County
POLYGON (..., ...)  Lancaster County
```

**Comment by jiayuasu** [comment]
@zongsizhang Please handle this.

**Comment by zongsizhang** [comment]
I'm working on this

**Comment by zongsizhang** [comment]
@chadwilcomb @jiayuasu Sorry for late response.
This is a very good point.
Actually spark itself support the format "filepath/*" as input path, which will add all sub-directory into input path list.
And I actually handled this case. If you do so, Geospark can tell that you give multiple paths and will load them parallel.
Just make sure that in your directory, the recursive loop is no more than 1, and you don't have other files in the same level with your shapefile directories. And different .shp should be put in different directory.
So actually now for GeoSpark we just miss a parser which can take a directory and extract sub paths, I'll put my hand on it. and try to make it in next release.

**Comment by OmkarNeogi** [comment]
@zongsizhang Could you please explain the ideal condition for *-based wildcard reads?
Could you please let me know if the following directory structure is expected to work?

**Format 1**
- outer_directory
  |- dir_1
  |  |- 1.shp
  |  |- 1.shx
  |  |- 1.dbf
  |
  |- dir_2
  |  |- 2.shp
  |  |- 2.shx
  |  |- 2.dbf

In such a case, would a read like: `ShapefileReader.readToGeometryRDD(sc, "./outer_directory/*")` be expected to work?
Both these directories containing shape files are a part of the same dataset, and there are a lot of them.
If not, what is the ideal directory structure?

**Comment by jiayuasu** [comment]
Hi Omar,

Please try to both the solutions:

(1) put all shp shx dbf of in the same directory. Then use the wildcard
directory/*
(2) try the one you put and Then use the wildcard directory/*

   - outer_directory
   |- dir_1
   | |- 1.shp
   | |- 1.shx
   | |- 1.dbf
   |
   |- dir_2
   | |- 2.shp
   | |- 2.shx
   | |- 2.dbf

Thanks,
Jia

------------------------------------

Jia Yu,

Ph.D. Student in Computer Science

Arizona State University <http://www.asu.edu/>

Reach me via Jia Yu's Homepage <http://www.public.asu.edu/~jiayu2/> | GitHub
Repositories <https://github.com/jiayuasu>

**Comment by OmkarNeogi** [comment]
Hi @jiayuasu thank you for your response.

With a file structure as follows:
outer_dir
|- 1
| |- 0101.shp 
| |- 0101.prj 
| |- 0101.shx 
| |- 0101.dbf
| |- 0102.shp 
| |- 0102.prj 
| |- 0102.shx 
| |- 0102.dbf
...
I tried reading the files (read each files with a wildcard as "0101*" and then unioning all files into one rdd).

This seems to work in reading the shapefile to geometries. However, there is a metadata field in the shapefile that does not seem to be passed on when reading using the readToGeometryRdd. This metadata field is available when parsing using ogr2ogr though. Could you recommend what I should do please?
