### ISSUE TITLE
getUserData with GeoJson returned String that isn't Json

### ISSUE THREAD

**Issue by netanel246** [apache/sedona#254]
## Expected behavior
When reading GeoJson file, the getUserData function need to return json, or at least HashMap<String, Object> in order to transform it to json
## Actual behavior
The getUserData returned String, in the form of: 
`{name1=value1, name2=value2,..}`
## Steps to reproduce the problem

1. Read a geoJson file into a rdd(e.g. polygons)
2. Define new rdd named it res
2. On res execute map , and for each geometry execute getUserData().toString()
3. print `res.take(5).mkstring(",") `to see the content of that rdd

## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Scala

**Comment by netanel246** [comment]
I've looked at the [FormatMapper] class (https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/formatMapper/FormatMapper.java)
especially this code:
```
if (feature.getProperties()!=null)
                {
                    if (hasIdFlag)
                    {
                        this.otherAttributes +="\t" + feature.getProperties();
                    }
                    else this.otherAttributes +=feature.getProperties();
                }
                geometry.setUserData(otherAttributes);
```
I was thinking to define otherAttributes as HashMap[String, Object], I'ts make sense for the json function,
but less for the other readers(WKT, WKB).
Or maybe refactor it to handle json differentlly?

**Comment by jiayuasu** [comment]
@netanel246 This part in FormatMapper should have different logic for GeoJSON. I am working on a solution. But just too busy to finish it.
