### ISSUE TITLE
ST_GeomFromWKT is not working for Polygon with Hole

### ISSUE THREAD

**Issue by Bhavesh-Joshi** [apache/sedona#256]
I am trying to create a polygon object using ST_GeomFromWKT. The String I am using for the same is as follows:
String customPolygon = new String("POLYGON((67.57 23.41, 67.57 53.41, 87.57 53.41, 87.57 23.41, 67.57 23.41),(75.23 33.41, 75.23 43.41, 85.23 43.41, 85.23 33.41, 75.23 33.41))");

Expected object  is  either this MULTIPOLYGON (((67.57 23.41, 67.57 53.41, 87.57 53.41, 87.57 23.41, 67.57 23.41), (75.23 33.41, 75.23 43.41, 85.23 43.41, 85.23 33.41, 75.23 33.41))) or POLYGON ((67.57 23.41, 67.57 53.41, 87.57 53.41, 87.57 23.41, 67.57 23.41), (75.23 33.41, 75.23 43.41, 85.23 43.41, 85.23 33.41, 75.23 33.41))

However GeoSpark is converting it to below mentioned object. It is making a multi polygon object with two separate outer rings. What I want is a polygon with one outer and one inner ring.
The object created by GeoSpark looked like: MULTIPOLYGON (((67.57 23.41, 67.57 53.41, 87.57 53.41, 87.57 23.41, 67.57 23.41)), ((75.23 33.41, 75.23 43.41, 85.23 43.41, 85.23 33.41, 75.23 33.41)))

Please let me know where I am going wrong.

GeoSpark version = 1.1.3

Apache Spark version = 2.2.0

JRE version = 1.8

API type = Java

**Comment by jiayuasu** [comment]
@Bhavesh-Joshi I think this a bug in JTS WKT reader... GeoSpark internally calls a customized version of JTS to read WKT. When it reads polygon with holes, automatically make it to separate polygons.

Not sure what's going on here, I checked JTS source code, it looks correct.
https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/io/WKTReader.java

**Comment by jiayuasu** [comment]
I guess no. The source code of both sides looks identical.

------------------------------------

Jia Yu,

Ph.D. Student in Computer Science

Arizona State University <http://www.asu.edu/>

Reach me via Jia Yu's Homepage <http://www.public.asu.edu/~jiayu2/> | GitHub
Repositories <https://github.com/jiayuasu>

Follow GeoSpark on Website <http://datasystemslab.github.io/GeoSpark/> |
GitHub <https://github.com/DataSystemsLab/GeoSpark> | Twitter
<https://twitter.com/GeoSpark_ASU>

**Comment by filip-cz** [comment]
ST_GeomFromGeoJSON behaves exactly the same faulty way:
ST_GeomFromGeoJSON('{
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
        [[0, 0],[10,0],[0,10],[0,0]],
        [[2, 2], [3,2], [2,3],[2,2]]
    ]
  },
  "properties": {"name": ""}
}')

returns MULTIPOLYGON (((0 0, 10 0, 0 10, 0 0)), ((2 2, 3 2, 2 3, 2 2)))
