### ISSUE TITLE
Not able to run Spatial queries on Google Dataproc SparkSQL job. 

### ISSUE THREAD

**Issue by sanjayio** [apache/sedona#267]
I am trying to a spatial join query job with Google Dataproc. I have given the following jars with the job: 1. geospark-1.1.3.jar
2. geospark-sql_2.2-1.1.3.jar
3. geospark-viz-1.1.3.jar
When I submit the job the job fails with the error the "Error in query: Undefined function: 'ST_Contains'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 23"
This is the query I am trying to run "insert into geospark_test_orc select utc_timestamp, advertiser_id, os, os_version, lat, lon, place_name, place_type from poi_2018_08_24_orc, (select stusps, ST_GeomFromWKT (wkt) as geom from state_boundaries_orc where stusps='CA') where ST_Contains(geom, ST_Point(lon, lat));"

## Settings
GeoSpark version = 1.1.3

Apache Spark version = 2.2

**Comment by jiayuasu** [comment]
@sanjay-94 Make sure you register GeoSparkSQL: 
http://datasystemslab.github.io/GeoSpark/tutorial/sql/#initiate-sparksession

```
.config("spark.serializer", classOf[KryoSerializer].getName)
.config("spark.kryo.registrator", classOf[GeoSparkVizKryoRegistrator].getName)
```

**Comment by sanjay-94** [comment]
The job still fails even after adding the following configurations
![image](https://user-images.githubusercontent.com/11581263/44824300-26993e00-ac48-11e8-89c8-e7777185a416.png)
I still get the same error. Is there any other configuration i am missing?

**Comment by jiayuasu** [comment]
@sanjay-94 I guess you misunderstood some settings. Please read the answer I just wrote:
https://github.com/DataSystemsLab/GeoSpark/issues/268

If you want to run Spark scala shell on Google DataProc, you should follow the conf like this:

> --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.kryo.registrator=org.datasyslab.geosparkviz.core.Serde.GeoSparkVizKryoRegistrator

After entering scala shell, you must register GeoSparkSQL like this, then you can run GeoSparkSQL.

```
import org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator
GeoSparkSQLRegistrator.registerAll(spark);
val df = spark.sql("select ST_GeomFromWKT(\"POINT (30 10)\") as col0")
df.show
```

**Comment by sanjay-94** [comment]
Got it. Will you be supporting SparkSQL CLI anytime soon?

**Comment by jiayuasu** [comment]
I guess I can support it soon. See #268
