### ISSUE TITLE
make custom optimizations in catalyst more stable to upgrades

### ISSUE THREAD

**Issue by geoHeil** [apache/sedona#280]
<img width="942" alt="deep_dive_into_query_execution_in_spark_sql_2_3_with_jacek_laskowski__continued__720p_60fps_h264-128kbit_aac_" src="https://user-images.githubusercontent.com/1694964/46850326-cd4e2e00-cdf3-11e8-8870-9e1bfb821c10.png">

spark seems to recently support some kind of stable API to do undocumented things. GeoSpark should consider to use this instead of the hacks which currently require a different variant of registration for each version of spark.

**Comment by jiayuasu** [comment]
This seems to only allow register logical plan rules and physical plan strategies? I hope it can provide a generic way to register Expressions into Spark catelog rather than register them as UDF.
