### ISSUE TITLE
Join big dataset of points with small dataset of geometry

### ISSUE THREAD

**Issue by manjeee** [apache/sedona#296]
## Expected behavior
I have loaded a huge point's dataset from dataframe and geometry dataset from ESRI-SHP File. 
I repartitioned huge dataset of 14 billions points into 10000 partitions and used ST_PointFromText to create a temporary view of points. SHP file contains 90 polygons, I loaded it and then apply ST_GeomFromWKT, created a view of geometry, so there is only 90 partitions. If I would try repartition this dataset, the most partitions will be empty. I join them by using ST_Contains sql query.

## Actual behavior
When I'm trying to join these datasets I got only 57 partitions to process. And there is a lot of FetchFailedExceptions because of this small amount of resulting partitions. I was trying to set .config("geospark.join.numpartition", "10000") but the error was occured about too huge amount of partitions. So can you advice please how to optimize this kind of join?

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.2.0

JRE version = 1.8

API type = Scala

**Comment by MahzadK** [comment]
UP?
