### ISSUE TITLE
can GeoSpark reproject with proj4 string("init=epsg:4326") like geopandas ?

### ISSUE THREAD

**Issue by FCtj** [apache/sedona#315]
I'm dealing with my korean custom epsg shp file and want to reproject to wgs84 with spark
cause It takes time by python-geopands or ogr2ogr or postgis
so I want to ask if I can do that job like below code

// geopandas reprojection
gdf = gdf.to_crs("+proj=eck4 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs")

**Comment by jiayuasu** [comment]
Hi @FCtj 
Two ways to do CRS transformation in GeoSpark,

For RDD API, use http://datasystemslab.github.io/GeoSpark/tutorial/rdd/#transform-the-coordinate-reference-system

For DataFrame/SQL API, use http://datasystemslab.github.io/GeoSpark/tutorial/sql/#transform-the-coordinate-reference-system
