### ISSUE TITLE
Converting Polygon shapefile to LineStringRDD

### ISSUE THREAD

**Issue by Corvexmanu** [apache/sedona#326]
## Expected behavior
Hi. I am trying to convert a polygon shapefile dataset into LineStringRDD. I am expecting to get each line of each polygon in the dataset as a LineStringRDD.  

## Actual behavior
I am getting this error: java.lang.Exception: [ShapefileRDD][getLineStringRDD] the object type is not LineString or MultiLineString type. It is Polygon

## Steps to reproduce the problem
val conf = new SparkConf().setAppName("Simple Application").setMaster("local[*]");    
val sc = new SparkContext(conf)
val path_CAD = "...\\Small_CAD_polygon.shp"
val cadPolyLinesRDD = ShapefileReader.readToLineStringRDD(sc, path_CAD )
[Small_CAD_polygon.zip](https://github.com/DataSystemsLab/GeoSpark/files/2836218/Small_CAD_polygon.zip)

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.4.0

JRE version = 1.8.0_191

API type = Scala

**Comment by jiayuasu** [comment]
Sorry, I don't understand what you want. Why do you want to load polygons into LineStringRDD? The format doesn't match. This cannot happen.
