### ISSUE TITLE
Writing in CSV/TXT file + outputs in console

### ISSUE THREAD

**Issue by Corvexmanu** [apache/sedona#327]
## Expected behavior
Hi. I am trying to write a CSV file containing all the coordinate points (X,Y) from a dataset of polygons(shapefile). I am expecting a CSV where each line is a pair of coordinates representing each line of each polygon from my original dataset. Then, I am going to use that file to create a LineStringRDD by using each pair with all the lines where each line will be each side of the polygons from the original dataset. 

## Actual behavior
When I am writing the csv file, if I use a small query window with about 10 polygons from my original dataset, I am getting the correct answer written in the CSV file. However, if I use all the polygons from the dataset (189), in some point the PrintWriter function stop to write in the file and produce the output in my console instead of inside of the file and it never ends. Each polygon has on average 6 to 8 lines. 

## Steps to reproduce the problem
[Small_CAD_polygon.zip](https://github.com/DataSystemsLab/GeoSpark/files/2836259/Small_CAD_polygon.zip)
![capture](https://user-images.githubusercontent.com/39916703/52340764-5f8dd800-2a5c-11e9-9040-2152dfccc381.PNG)

object App 
{  
  def main(args: Array[String]){
    val conf = new SparkConf().setAppName("Simple Application").setMaster("local[*]");    
    val sc = new SparkContext(conf)
    val path_CAD = "....\\Small_CAD_polygon.shp"
    val cadastralRDD = creatingCadPolygons(sc,path_CAD)
    val linesRDD = creatingPolylines(sc,path_CAD,cadastralRDD)
}

def creatingCadPolygons (sc:SparkContext, path:String): PolygonRDD = {
    val cadastralRDD = ShapefileReader.readToPolygonRDD(sc, path)
    println("creatingCadPolygons executed")
    return cadastralRDD    
  }

def creatingPolylines (sc:SparkContext, path:String,  cadastralRDD:PolygonRDD): LineStringRDD = {  
    val result = cadastralRDD.getRawSpatialRDD
    val writer = new PrintWriter(new File("...\\Polylines.csv"))    
    val polygons = result.count() - 1
    for( p <- 0 to polygons.toInt){      
      val coordinates = result.collect().get(p).getCoordinates().count(x => true) - 1 
      for( c <- 0 to coordinates){
        if (c != coordinates){
          writer.write(result.collect().get(p).getCoordinates.apply(c).getOrdinate(0) + "," + result.collect().get(p).getCoordinates.apply(c).getOrdinate(1) + "," + result.collect().get(p).getCoordinates.apply(c+1).getOrdinate(0) + "," + result.collect().get(p).getCoordinates.apply(c+1).getOrdinate(1) +"\r\n")
          Source.fromFile(".....\\Polylines.csv").foreach { x => print(x) }
        }
       }
          }         
    writer.close()
    println("Polylines.csv created")

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.4.0

JRE version = 1.8.0_192

API type = Scala

**Comment by jiayuasu** [comment]
Polygon coordinates have one extra coordinate which is same as the initial coordinate.

**Comment by Corvexmanu** [comment]
Hi. yes, that is the format used in MAPinfo to identify a polygon. The original data comes from MAPinfo, then i created the shapefile and use it. Do you think that that particular format insert any issue?
