### ISSUE TITLE
Release with Spark 2.4 and Scala 2.12

### ISSUE THREAD

**Issue by jasonmoore2k** [apache/sedona#340]
Would it be possible to make a release available for Spark 2.4?  Ideally, this should also be cross-compiled to Scala 2.12 (along with Scala 2.11), given the intention is for 2.12 to become the default Scala version from Spark 3.0 onward.

**Comment by jiayuasu** [comment]
@jasonmoore2k GeoSpark-1.2.0 for Spark 2.3 supports Spark 2.3+ including 2.4.

We will consider to cross-compiled it to Scala 2.12. Currently, I believe the Scala code in GeoSpark is compatible for both Scala 2.11 and 2.12. If you are in rush, you can compile it by yourself

**Comment by heaven00** [comment]
I faced some issue with scala `2.12`, details https://github.com/DataSystemsLab/GeoSpark/issues/380

**Comment by Benji81** [comment]
a little up,  Support for Scala 2.11 is deprecated as of Spark 2.4.1 and will be removed in Spark 3.0.

Upgrading to scala 2.12 Would be great

**Comment by jiayuasu** [comment]
@Benji81 This is our first priority now.

**Comment by kyprifog** [comment]
@jiayuasu What is the status of this?   Would like to at least have scala 2.12 spark 2.4.x at some point.  Any way I can help?

**Comment by jiayuasu** [comment]
@kyprifog We will be providing the release under the Apache Sedona (incubating). If you want to help, you can create a script or separate branch to generate the release of Sedona in Scala 2.12. I will accept this PR.
