### ISSUE TITLE
GeoJsonReader not found

### ISSUE THREAD

**Issue by nd-minh** [apache/sedona#347]
Hello everyone, I am new to GeoSpark and I am trying to read a GeoJSON file to try to perform some simple queries. Following the tutorial on GeoSpark homepage, I tried to import the libraries and read my file as follows:

`import scala.collection.immutable.List;`
`import com.vividsolutions.jts.geom.{Coordinate, Envelope, GeometryFactory}`
`import org.datasyslab.geospark.spatialOperator.{JoinQuery, KNNQuery, RangeQuery}`
`import org.datasyslab.geospark.spatialRDD.{CircleRDD, PointRDD, PolygonRDD}`

`val spatialRDD = GeoJsonReader.readToGeometryRDD(sc, "hdfs://node-master:9000/dataset/Sydney.osm.geojson");`

However, I got the error: not found: value GeoJsonReader. Can you please help me with this problem. I cannot find information about the 'GeoJsonReader' function on the GeoSpark homepage. Thank you very much.

## Expected behavior
A generic SpatialRDD is created from the GeoJSON file

## Actual behavior
error: not found: value GeoJsonReader

GeoSpark version = 1.1.0

Apache Spark version = 2.2.3

JRE version = 1.8.0

API type = Scala

**Comment by jiayuasu** [comment]
@minh2908 There is no GeoJsonReader in GeoSpark 1.1.0. It is included in GeoSpark 1.2.0
