### ISSUE TITLE
Feature Request: ST_Cast

### ISSUE THREAD

**Issue by harryprince** [apache/sedona#350]
Goal: make a`st_cast` function to convert different geometry type.

example: `st_cast(polygon_geom,"MULTIPOINT")`, which convert polygon geometry to multipoint geometry.

The transformation flow as follows:

![](https://image-static.segmentfault.com/738/576/738576080-5b76c6474c8c4)

this idea comes from `sf` R package:

https://cran.r-project.org/web/packages/sf/vignettes/sf3.html#type_transformations

**Comment by AntonPeniaziev** [comment]
@harryprince , @jiayuasu , I would like to work on this issue, however there are some arrow directions in your graph that need to be defined. R specifies 4 bullets which are pertty clear :

> convert from XX to MULTIXX, e.g. LINESTRING to MULTILINESTRING
convert from MULTIXX to XX if MULTIXX has length one (else, it will still convert but warn about loss of information)
convert from MULTIXX to XX if MULTIXX does not have length one, but it will warn about the loss of information
convert GEOMETRYCOLLECTION of length one to its component if

when on graph there are few unclear cases:

1. point -> linestring (is it a valid geometry?)
2. linestring-> polygon 
3. multilinestring ->polygon (should user specify order? what about validity checkk?)
there are more. Can you please elaborate on the above?

Thanks

**Comment by harryprince** [comment]
`geospark` `st_cast` just like `sf` counterpart.

**Comment by harryprince** [comment]
@AntonPeniaziev you can checkout the `sf` document and try examples.

1. point -> linestring, is converting  a sequential points into linestring by the default order
2. linestring -> polygon, sometime maybe not valid
3. the same as previous

@AntonPeniaziev
