### ISSUE TITLE
Missing class GeoSparkKryoRegistrator

### ISSUE THREAD

**Issue by lyncher33** [apache/sedona#353]
## Expected behavior
Initiate a new Spark Session in order to utilize GeoSpark and run Spatial Spark SQL queries

## Actual behavior
Get error when attempting to initiate session calling SparkSession.builder() as per below...
CODE:
var sparkSession = SparkSession.builder()
     .appName("TEST_GeoSpark")
     // Enable GeoSpark custom Kryo serializer
     .config("spark.serializer", classOf[KryoSerializer].getName)
     .config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
     .getOrCreate()

RESULTS/ERROR:
error: not found: type GeoSparkKryoRegistrator
                     .config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)

## Settings
GeoSpark version = 1.2.0
Apache Spark version = 2.4
JRE version = 1.8
API type = Scala

**Comment by fmarchand** [comment]
How do you load the geospark dependency ?
