### ISSUE TITLE
[Question] Lazy evaluation in geospatial calculations?

### ISSUE THREAD

**Issue by pedromorfeu** [apache/sedona#354]
## Question
Is GeoSpark taking advantage of Spark lazy evaluation for geospatial calculations? 

Say you perform a spatial join:
```
objectRDD.analyze()

objectRDD.spatialPartitioning(GridType.KDBTREE)
queryWindowRDD.spatialPartitioning(objectRDD.getPartitioner)

JoinQuery.SpatialJoinQuery(objectRDD, queryWindowRDD, true, false)
```

Is GeoSpark performing the calculation immediately or only when an action is invoked?

**Comment by jiayuasu** [comment]
Hi Pedro,

GeoSpark does take advantage of the lazy evaluation. The spatial
partitioning function call will happen right away but some steps in
SpatialJoinQuery may not be executed if you don't persist the query result.

Thanks,
Jia

------------------------------------

Jia Yu,

Ph.D. Student in Computer Science

Arizona State University <http://www.asu.edu/>

Reach me via Jia Yu's Homepage <http://www.public.asu.edu/~jiayu2/> | GitHub
Repositories <https://github.com/jiayuasu>

**Comment by pedromorfeu** [comment]
What about `spatialRDD.analyze()`?

**Comment by jiayuasu** [comment]
@pedromorfeu 

According to the source code of spatialRDD.analyze(): https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java#L502

this function will trigger a reduce-like function **aggregate**. Therefore, the analyze function will be executed right away once you call it. And all lazy evaluated functions before the call **spatialRDD.analyze()** will take place all together along with the analyze().

**Comment by pedromorfeu** [comment]
Can it be avoided somehow? I mean, is there away to create spatial partitioning without calling analyze first?

**Comment by jiayuasu** [comment]
@pedromorfeu 

Yes, it can be avoided for sure.

Please look at this overloaded analyze() function: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java#L514

What you need to provide is that the maximum spatial boundary of all your involved spatial data (this can be approximate but it should cover all your spatial data involved in the join) and the approximate total count of this SpatialRDD.

Then you can avoid the time-consuming aggregation.

**Comment by pedromorfeu** [comment]
That's nice, thanks. 

Now, I can approximate the spatial envelope easily. But the count is harder. Is it really needed?

**Comment by jiayuasu** [comment]
@pedromorfeu You can use something like this to get an approximate count quickly. This count is needed in spatial partitioning:
```
val cntInterval = df.rdd.countApprox(timeout = 1000L,confidence = 0.90)
```
