### ISSUE TITLE
shapefiles are loaded into 1 partition

### ISSUE THREAD

**Issue by GiorgosMandi** [apache/sedona#356]
## Expected behavior
Load shapefile into multiple partitions avoiding repartitioning it. 

## Actual behavior
I'm trying to load a big shapefile (.shp 1.9Gb, .dbf 2Gb)  into multiple partitions but it is always read into a single one forcing me to repartition, which is a very time-consuming process. Converting the same shapefile into a CSV, apache spark is reading it into 40+ partitions.

So I would like to ask if there is any way to directly load the shapefile into multiple partitions.

## Steps to reproduce the problem
//Java Code
SpatialRDD<Geometry> spatialRDD = ShapefileReader.readToGeometryRDD(java_sparkContext, input);
Dataset dt = Adapter.toDf(spatialRDD, spark)
//  dt.javaRDD().getNumPartitions() is always 1

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.4.0

JRE version = 1.8

API type = Java

**Comment by jiayuasu** [comment]
@GiorgosMandi GeoSpark shapefilereader doesn't control the number of partitions loaded by Spark or Hadoop. But I am not sure whether the shapefile is always loaded into a single big partition.

My recommendation is that, put your shapefile onto HDFS. This will automatically partition your shapefile to HDFS partitions. Then use GeoSpark shapefile loader to read the HDFS path. I believe the loaded RDD will have many partitions.

**Comment by GiorgosMandi** [comment]
I am already running it in HDFS and the shapefile is always loaded into 1 partition.
Now I believe it is happening because the .shx file is smaller than HDFS' block size and therefore it is not partitioned across the cluster.
Anyway, I'm closing the Issue since it's not GeoSpark that causes the problem!

Thank you very much!!

**Comment by GiorgosMandi** [comment]
I ensured that the shapefile is partitioned across the cluster and I even reduced the size of the dfs.block.size in order the .shx file to be partitioned as well. As a result 
the .dbf file is divided into 59 blocks
the .shp file is divided into 55 blocks
and the .shx file is divided into 3 blocks (its actual size is 88MB)
(using 1 replication)

But still, the shapefile is always loaded into a SpatialRDD of a single partition.

**Comment by GiorgosMandi** [comment]
I ensured that the shapefile is partitioned across the cluster and I even reduced the size of the dfs.block.size in order the .shx file to be partitioned as well. As a result 
the .dbf file is divided into 59 blocks
the .shp file is divided into 55 blocks
and the .shx file is divided into 3 blocks (its actual size is 88MB)
(using 1 replication)

But still, the shapefile is always loaded into a SpatialRDD of a single partition.

**Comment by jiayuasu** [comment]
@GiorgosMandi I will look into this.

**Comment by SW186000** [comment]
@jiayuasu @GiorgosMandi Hi! I suppose that reason is this ShapeInputFormat class uses CombineFileInputFormat. Even though a shape file is devided into several blocks, at first Spark merges them to a one file and process it in one partition. I don't know whether we can implement new InputFormat class or not.

**Comment by jiayuasu** [comment]
@SW186000 Thank you very much for this reminder! This is a very good point.

@zongsizhang Did you have a specific reason why you implement the shapefile reader using CombineFileInputFormat?
