### ISSUE TITLE
ST_Transform UseLongitudeLatitudeOrder:Boolean does not work

### ISSUE THREAD

**Issue by Wrussia** [apache/sedona#358]
## Expected behavior

I should get different result with different UseLongitudeLatitudeOrder:Boolean

## Actual behavior

Result is the same

## Steps to reproduce the problem

```
val polygon = "POLYGON ((110.54671 55.818002, 110.54671 55.143743, 110.940494 55.143743, 110.940494 55.818002, 110.54671 55.818002))"

spark.createDataset(Seq(polygon))
  .withColumn("geom", expr("ST_GeomFromWKT(value)"))
  .createOrReplaceTempView("df")

spark.sql("select ST_Transform(geom, 'EPSG:4326', 'EPSG:32649', false, false)  from df")
  .show(false)

spark.sql("select ST_Transform(geom, 'EPSG:4326', 'EPSG:32649', true, false)  from df")
  .show(false)
```
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|st_transform(geom, EPSG:4326, EPSG:32649, false, false)                                                                                                                                                   |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|POLYGON ((2395963.2501665875 11346215.41937216, 2412263.098391083 11323989.282104466, 2449404.4345494257 11350968.919029245, 2432753.7547044493 11373617.661381979, 2395963.2501665875 11346215.41937216))|
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|st_transform(geom, EPSG:4326, EPSG:32649, true, false)                                                                                                                                                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|POLYGON ((2395963.2501665875 11346215.41937216, 2412263.098391083 11323989.282104466, 2449404.4345494257 11350968.919029245, 2432753.7547044493 11373617.661381979, 2395963.2501665875 11346215.41937216))|
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Scala

**Comment by Wrussia** [comment]
I've expected 
`POLYGON ((471596.69167460164 6185916.951191288, 471107.5623640998 6110880.974228167, 496207.109151055 6110788.804712435, 496271.31937046186 6185825.60569904, 471596.69167460164 6185916.951191288))`

Now I'm trying to play back it in GeoSpark tests, but regardless of UseLongitudeLatitudeOrder getting expected result. Thats very strange.

**Comment by jiayuasu** [comment]
@Wrussia This is very strange. If you look at the source code here: https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala#L208

You will notice that GeoSpark did take into account the LonLat order. Several days ago, in Issue https://github.com/DataSystemsLab/GeoSpark/issues/357, he also tried "UseLongitudeLatitudeOrder", it actually worked.

**Comment by Wrussia** [comment]
I found problem, that when you use ST_Transform first time, it sets `System.setProperty("org.geotools.referencing.forceXY", {your value, true by default})` which will apply all next queries, regardless parameter that you set. I don't know how it works for now.

I have a feeling, that I had a case, when that parameter was set to false by default and this is already a real problem.

**Comment by Wrussia** [comment]
Thats really strange, I've wrote a UDF function which counts area of polygon, which I want call from python. So, if I call my function before GeoSpark function,  `UseLongitudeLatitudeOrder` is ignored.

But behavior of `UseLongitudeLatitudeOrder` parameter is still don't right, it defining for all session at first time ST_Transform called. It's doubled strange, that I can set it to `false`, while `org.geotools.referencing.forceXY` defining to `true` every time when function called.

**Comment by SW186000** [comment]
@Wrussia @jiayuasu I think that System.setProperties can't be affected multiple times because it is JVM parameter. "org.geotools.referencing.forceXY" should be set in extraJavaOptions(only once).
