### ISSUE TITLE
GeoSparSQL Code failing with memory issues

### ISSUE THREAD

**Issue by ChitturiPadma** [apache/sedona#361]
## Expected behavior
I  have point DataFrame with around 3 million point and complex polygon DataFrame which has around 700k polygons. Each polygon has geometry ranging from 500 points to nearly 1000 points. I am running ST_WITHIN(pointdf.point, polygondf.polygon). 

## Actual behavior

Failing with spark memory issue -
Lost task 7.0 in stage 10.0 (TID 8219, 10.120.11.156, executor 17): ExecutorLostFailure (executor 17 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 37.6 GB of 37 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.3

JRE version = 1.8

API type = Scala 
Added all necessary settings such as -

sparkSession = SparkSession.builder().
      config("spark.serializer",classOf[KryoSerializer].getName).
      config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName).
      config("geospark.join.gridtype","kdbtree").
     config("spark.sql.shuffle.partitions", 2000)
      master("yarn").appName("GeoSpatialAnalysis").getOrCreate()

Also repartitioned pointDf and polygonDf to 2000
Still having the same problem.

**Comment by jiayuasu** [comment]
@ChitturiPadma Thanks for using GeoSpark!

Sometimes the performance of GeoSparkSQL isn't ideal.

To do this in GeoSpark RDD API, you can read the doc here: http://datasystemslab.github.io/GeoSpark/tutorial/rdd/#write-a-spatial-join-query

The code snippet looks like this:

```
val considerBoundaryIntersection = false // Only return gemeotries fully covered by each query window in queryWindowRDD
val usingIndex = false

objectRDD.analyze()

objectRDD.spatialPartitioning(GridType.KDBTREE)
queryWindowRDD.spatialPartitioning(objectRDD.getPartitioner)

val buildOnSpatialPartitionedRDD = true // Set to TRUE only if run join query
val usingIndex = true
queryWindowRDD.buildIndex(IndexType.QUADTREE, buildOnSpatialPartitionedRDD)

val result = JoinQuery.SpatialJoinQueryFlat(objectRDD, queryWindowRDD, usingIndex, considerBoundaryIntersection)
```

This join query is equivalent to ST_Within

``` 
SELECT superhero.name
FROM city, superhero
WHERE ST_Contains(city.geom, superhero.geom);
```

Moreover, GeoSpark RDD API can be used with SQL API together. This way, you only need to write join code in RDD API and still enjoy the benefits of SQL. Here is a fully runnable example of RDD + SQL for join query:
https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/scala/org/datasyslab/geosparksql/adapterTestScala.scala#L135

**Comment by ChitturiPadma** [comment]
@jiayuasu 
Here is the Spatial RDD code -
 val unitProfileAttributes = sparkSession.read.parquet("/points_jsonfile")

    val unitProfileAttributesSpatialDf = unitProfileAttributes
      .withColumn("pointshape", callUDF("ST_Point", $"geo_location_longitude_decimal", $"geo_location_latitude_decimal"))
      .select("pointshape", "unit_uuid", "geo_city_search_term_full_name")
      .repartition(2000)


    val pointDfColumnList = unitProfileAttributesSpatialDf.columns.toList
    val pointRDD = Adapter.toSpatialRdd(unitProfileAttributesSpatialDf, pointDfColumnList)
    pointRDD.analyze()



    val geoPlacesJson =  spark.read.parquet("/polygons_file")

    val geoPlacesJsonSelected = geoPlacesJson
      .select($"term.geography.defaultGeometry", $"term.geography.location.lat", $"term.geography.location.lng",  $"term.name.en.full")


    val polygonDf = geoPlacesJsonSelected
      .withColumn("polygonshape", callUDF("ST_GeomFromWKT", $"defaultGeometry"))
      .select("polygonshape", "full")

    val polygDfColumnList = polygonDf.columns.toList
    val polygonRDD = Adapter.toSpatialRdd(polygonDf, polygDfColumnList)
    polygonRDD.analyze()

    //Add partitioning
    pointRDD.spatialPartitioning(GridType.KDBTREE)


    //ADD INDEX
    val buildOnSpatialPartitionedRDD = true // Set to TRUE only if run join query
    pointRDD.buildIndex(IndexType.QUADTREE, buildOnSpatialPartitionedRDD)
    polygonRDD.spatialPartitioning(pointRDD.getPartitioner)

    //SPATIAL JOIN
    val considerBoundaryIntersection = false // Only return gemeotries fully covered by each query window in queryWindowRDD
    val usingIndex = true
    val result = JoinQuery.SpatialJoinQueryFlat(pointRDD, polygonRDD, usingIndex, considerBoundaryIntersection)


    val joinResultDf = Adapter.toDf(result, pointDfColumnList, polygDfColumnList,sparkSession)

    joinResultDf
      .write.mode(SaveMode.Overwrite)
      .parquet("s3:" +"/path")

However this is still throwing below issue -
Lost task 11.3 in stage 22.0 (TID 6447, 10.120.3.243, executor 157): ExecutorLostFailure (executor 157 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 38.4 GB of 37 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.

Any other imporvement you suggest ?

**Comment by Wrussia** [comment]
I have the same problem. I need to find neighbours polygons (~1 million very big polygons), job falls with same exception. I'm trying to find neighbours in cities separately and that helps, but performance not good. I think it's skew on one partition, we need to do something with that

**Comment by ChitturiPadma** [comment]
@Wrussia How would you identify that there is skew in the partitions...you mean to say neighbouring polygons having overlapping regions will have these problem ? Visualizing the polygoon data to some extent will help? In case of structured data, when there is skew, we do group by take counts and look at the distribution to understand the skew. Just wondering how to identify skew here ?

**Comment by Wrussia** [comment]
@ChitturiPadma there is happens something like group by, data groups by "spatial" partitions. You can visualise your spatial grid like 

```
import com.vividsolutions.jts.geom.{Envelope, Geometry, GeometryFactory}

val geometryFactory = new GeometryFactory()
val gridWKT = spatialRDD.getPartitioner.getGrids.toArray()
  .map { case x: Envelope => geometryFactory.toGeometry(x).toText.replace("POLYGON", "") }
  .mkString("MULTIPOLYGON(", ", ", ")")
```
(I did it for QuadTree and don't know will it work for others or not.)

And when too much data get into one rectangle, skew happened.

I'm trying to get out partition indices and join by them, so work will be with DataFrames instead of RDDs.

**Comment by Wrussia** [comment]
I found that I can get partitions ids with this code:
```
val javaRDD = geomDF
  .map { row =>
    row.getAs[Geometry]("geom")
  }.toJavaRDD

val spatialRDD = new SpatialRDD[Geometry]
spatialRDD.rawSpatialRDD = javaRDD

spatialRDD.analyze()
spatialRDD.spatialPartitioning(GridType.QUADTREE)

val partitionTreeBroadcasted = spark.sparkContext.broadcast(spatialRDD.partitionTree)

val findPartitions: Geometry => Array[Int] = { geom =>
  val env = geom.getEnvelopeInternal
  val partitionTree = partitionTreeBroadcasted.value

  val res = partitionTree.findZones(new QuadRectangle(env))
    .toArray
    .map { case x: QuadRectangle => x.partitionId.toInt }

  if (res.isEmpty) Array(-1) else res
}

val findPartitionsUdf = udf(findPartitions)

val geomWithKeyDF = geomDF.select(
  explode(findPartitionsUdf('geom)) as "spatial_key",
  'geom,
  'id
)
```

There you will find the skew with group by spatial key and you'll get the opportunity to use sort merge spatial join.

**Comment by jiayuasu** [comment]
@ChitturiPadma Another issue that raise my attention is that, in your code, you mentioned your polygons are very complex. 

(1) If your DataFrame contains lots of unnecessary columns, please consider removing them before doing the spatial join because all these non-spatial attributes will also be carried across the machines and increase the memory footprint. You can recovery these attributes by having a primary key although this may take extra time.

(2) If all your polygons intersect each other and overlay on each other, GeoSpark spatial partitioning may not partition them efficiently. If this is the case, consider using the Spark original broadcast join or split the point/polygon DataFrame to several sub DataFrames, do spatial join separately and merge the query result later.

**Comment by Wrussia** [comment]
@jiayuasu I have similar problem, complex polygons with area more then 1km^2, they have the skew (up to 5000 polygons each side of partition) and I need to find polygons with distance within 500m and get distance between them. 

I feels that distance function works very slow, it counts distance between each point between (https://github.com/locationtech/jts/blob/4c7c8a8e968fb5c525edeb0c7d5479326ac785a3/modules/core/src/main/java/org/locationtech/jts/operation/distance/DistanceOp.java#L30), and I have no idea what to do with that. Do you know any library with some tricky optimal algorithm? JTS saying that using Voronoi techniques or spatial indexes is much more optimal (O(n log n ) complexity of Voronoi) but I didn't found any library with realisation. 

So, I found that shuffling my data is a very small part of my join. I tried to join my data separately, but it have similar operation count as join all in one query. But separate the data, join it and merge at the end isn't comfortable. My realisation with getting spatial index and joining DataFrames works, but I'm not happy with this performance.

**Comment by jandam** [comment]
I think that you can use as inspiration FacetSequence support from JTS. It allows you to compute distance from line strings. So you have to check if you are inside polygon - distance = 0.0.
