### ISSUE TITLE
ST_Distance outputs incorrect distances in UK Region

### ISSUE THREAD

**Issue by yogeshpat3l** [apache/sedona#366]
ST_Distance outputs incorrect distances in UK Region, though this function works fine and outputs correct values if the points are taken from the Indian and Indonesian regions as I have used this function for the points in these regions. Is there any solution to get correct distances?

## Expected behavior
Distance between points **51.5241181900,-0.1372587800** and **51.5217700300,-0.1548252300** should be approx **1243.4m**. The points are in the region of the UK

## Actual behavior
But the distance between points **51.5241181900,-0.1372587800** and **51.5217700300,-0.1548252300** calculated is **1970.6740933528322m** which is not correct.

## Steps to reproduce the problem
**Run below query** 
select src, nbr, google_distance, radians(ST_Distance(ST_Point(CAST(nlong as Decimal(16,10)),CAST(nlat as Decimal(16,10))), ST_Point(CAST(slong as Decimal(16,10)),CAST(slat as Decimal(16,10))))*6371000.0) as nbrToSrcDistance from RawData

**Using below CSV**
src,slat,slong,nbr,nlat,nlong,st_distance,google_distance
53663_2,51.5241181900,-0.1372587800,13832,51.5213376800,-0.1388425200,355.8145263680459,328.1
53663_2,51.5241181900,-0.1372587800,14259,51.5217700300,-0.1548252300,1970.6740933528322,1243.4

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.3.1

JRE version = 1.8

API type = Java

**Comment by jiayuasu** [comment]
@yogeshpat3l Please note that, GeoSpark does not control the unit of distance. It always uses the Euclidean distance formula to compute the distance. To obtain the correct distance from ST_Distance, you need to project the coordinate from WGS84 to a proper planar coordinate reference system. Please refer to this section in GeoSpark documentation: https://datasystemslab.github.io/GeoSpark/tutorial/sql/#transform-the-coordinate-reference-system

**Comment by yogeshpat3l** [comment]
@jiayuasu so you are saying that before using ST_Distance I need to transform the WGS84 Points into EPSG:27700 (UK coordinate system), right? Like below

select src, nbr, slat, slong, nlat, nlong, google_distance, ST_Distance(ST_Transform(ST_Point(CAST(nlong as Decimal(16,10)),CAST(nlat as Decimal(16,10))), 'epsg:4326', 'epsg:27700'), ST_Transform(ST_Point(CAST(slong as Decimal(16,10)),CAST(slong as Decimal(16,10))), 'epsg:4326', 'epsg:27700')) as st_distance  from RawData

If yes then I did the same but didn't get the correct distances, even this time the distances are kind of  EPSG:27700 coordinates. See below the output of the query

![image](https://user-images.githubusercontent.com/25293881/59425022-b9c7ec80-8df2-11e9-93ef-78be103759a8.png)

How do I get the correct distances in meters?

**Comment by SW186000** [comment]
@yogeshpat3l  you use longitude twice. Maybe it is a typo. 

select src, nbr, slat, slong, nlat, nlong, google_distance, ST_Distance(ST_Transform(ST_Point(CAST(nlong as Decimal(16,10)),CAST(nlat as Decimal(16,10))), 'epsg:4326', 'epsg:27700'), ST_Transform(ST_Point(CAST(slong as Decimal(16,10)),CAST(**slat** as Decimal(16,10))), 'epsg:4326', 'epsg:27700')) as st_distance from RawData

**Comment by Abraflare** [comment]
I seem to be having the same issue as above:
Taking two relatively close cities in the UK, Glasgow and Edinburgh, the distance between the cities is around 67km. 
Using EPSG:3857 I get the distance 119.37527km. 
Using a basic conversion from EPSG:4326 degrees to km (1 degree = 111.32km) I get 118.5171km, again incorrect.

Query:
SELECT 
'epsg:3857/1000' as system, 
ST_Distance(
   ST_TRANSFORM(ST_Point(-4.2576, 55.8652), 'epsg:4326', 'epsg:3857'), 
   ST_TRANSFORM(ST_Point(-3.1965, 55.9521), 'epsg:4326', 'epsg:3857'))/1000  as result

**Comment by jiayuasu** [comment]
@Abraflare There is a bunch of different coordinate reference systems for UK, like this one: https://epsg.io/27700

You can search "UK" on epsg.io. I am not an expert for CRS but I guess probably a proper CRS instead of EPSG:3857 will solve the problem.
