### ISSUE TITLE
DistanceJoinExec Optimization for cross join ?

### ISSUE THREAD

**Issue by pchanumolu** [apache/sedona#368]
I am trying to find all the geometry pairs in my dataset that are within 100 units distance from each other.

My Dataset schema looks like this.
<id: Long, wkb: String>

Here is the query I am trying. 

spark.sql("""SELECT
    t1.id as t1, t2.id as t2, ST_DISTANCE(ST_GeomFromWKB(t1.wkb), ST_GeomFromWKB(t2.wkb)))
FROM 
    mytable t1 
JOIN 
    mytable t2 
WHERE
    t1.wkb IS NOT NULL 
    AND 
    t2.wkb IS NOT NULL
    AND 
    (ST_DISTANCE(ST_GeomFromWKB(t1.wkb), ST_GeomFromWKB(t2.wkb))) < 100 """)

However, this is not using the DistanceQueryJoin optimization in GeoSpark. Here is the query plan I am seeing. 

== Physical Plan ==
Project [id#319L AS t1#317L, id#382L AS t2#318L,  **org.apache.spark.sql.geosparksql.expressions.ST_Distance$**   AS st_distance(st_geomfromwkb(wkb), st_geomfromwkb(wkb))#413]
+- **CartesianProduct** (( **org.apache.spark.sql.geosparksql.expressions.ST_Distance$**   / 1000.0) < 100.0)
   :  +- *(1) Filter (isnotnull(wkb#324)))

I looked into the code and looks like the optimizations are only considered for the Inner Joins. Is there any reason for supporting only Inner joins? 

Are there any plans of supporting the join optimization for the cross joins? 

In my case, I have 2million rows in my dataset. I need the optimizations here to make run this query quickly. Any suggestions on optimizing this are welcome. 

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.4.3

JRE version = 1.8

API type = GeoSpark-SQL

**Comment by pchanumolu** [comment]
@jiayuasu Can you please help here?

**Comment by jiayuasu** [comment]
@pchanumolu Currently there is no optimization for cross join. Some people were also looking for left outer join.

To optimize this query, the only way I can come up with for now is that, do the inner join first to get the inner join result. Then run another join to build your full cross-join table. If **the inner join result is small**, hopefully, the physical plan of the second join will become a HashJoin/Broadcast join which is much better the CartesianProduct join now.
