### ISSUE TITLE
Installation issues with GeoSpark-Zeppelin for Visualizing maps

### ISSUE THREAD

**Issue by viswanatharv** [apache/sedona#370]
Hi,

Seeing the issues while installing GeoSpark-Zeppelin for Visualizing the maps. Getting the below error. I have followed the steps mentioned in the URL [GeoSpark-Zeppelin](https://datasystemslab.github.io/GeoSpark/download/zeppelin/), but still not able to install and use the GeoSpark Viz. After all the steps, try to run the the notebook [GeoSpark-Zeppelin notebook template](https://datasystemslab.github.io/GeoSpark/image/geospark-zeppelin-demo.json). But the "geospark-zeppelin" button is not activated in spark sql interpreter. Is there any way to download the required dependencies and place it in local folder and make it work for GeoSpark-Zeppelin?

Error setting properties for interpreter 'spark.spark': Cannot fetch dependencies for org.datasyslab:geospark:1.2.0

GeoSpark version = 1.2.0

Apache Spark version =  2.2.1

JRE version = 1.8?

API type = Scala

**Comment by kuckjwi** [comment]
What you're saying is that you don't see a button?

**Comment by viswanatharv** [comment]
@kuckjwi, I am seeing the button and its disabled. Let me try one more time and get back to you

**Comment by kuckjwi0928** [comment]
@viswanatharv Yes, It was normal when I did it.
