### ISSUE TITLE
use more efficient spatial index

### ISSUE THREAD

**Issue by geoHeil** [apache/sedona#385]
Currently, geospark is based on the jts.STRTree. https://github.com/prestodb/presto/pull/13079 could be a great enhancement regarding memory pressure, i.e. implementing it using Hilbert Packed RTree (Flatbush)

**Comment by AntonPeniaziev** [comment]
@jiayuasu , should it be added to JTSplus?

**Comment by AntonPeniaziev** [comment]
@geoHeil , could you please elaborate on methods to perform benchmark testing for memory footprint? I still barely understand what are Flatbush pros over the STRTree and which kind of data could show it

**Comment by geoHeil** [comment]
I think https://github.com/prestodb/presto/pull/13079 has a good introduction. But for myself I am also not the expert here. I just heard of this and thought it could be really useful in geospark as well.
