### ISSUE TITLE
Runtime issue probably related to compiler ABI settings

### ISSUE THREAD

**Issue by tonio73** [apache/sedona#386]
## Actual behavior

Java/Scala error with stack trace showing some byte code compatibility issues : 
- KNNQuery.SpatialKnnQuery(...) =>   java.lang.ClassCastException: com.vividsolutions.jts.geom.Polygon cannot be cast to com.vividsolutions.jts.geom.Geometry
- RDD.analyze => java.lang.ClassCastException: org.datasyslab.geospark.spatialRddTool.StatCalculator cannot be cast to org.datasyslab.geospark.spatialRddTool.StatCalculator

## Steps to reproduce the problem

Call one of the above methods with an existing RDD

## Settings

GeoSpark version = 1.2

Apache Spark version = 2.4.4

JRE version = 1.8?

Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

API type = Scala (called from a Spylon-kernel or a spark-shell)

**Comment by jiayuasu** [comment]
@tonio73 Can you paste your complete code? This is probably because you didn't create your SpatialRDD properly.

**Comment by tonio73** [comment]
Thanks for the quick reply, I took some time to export to a proper spark application and it works there.

The ABI issue is really when creating the RDD from within a spark-shell (or notebook with spylon-kernel).

It would be very helpful for exploration purposes.

Any idea ?

Code is : 
```
var sparkSession = SparkSession
      .builder()
      .master("local[*]") // Delete this if run in cluster mode
      .appName("avalancheTest") // Change this to a proper name
      // Enable, GeoSpark, custom, Kryo, serializer
      .config("spark.serializer", classOf[KryoSerializer].getName)
      .config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
      .getOrCreate()

    GeoSparkSQLRegistrator.registerAll(sparkSession)

    val mountainZonesPath = "../data/n-datar-montagne-communes-s-r84"
    val mountainZonesRDD = ShapefileReader.readToGeometryRDD(sparkSession.sparkContext, mountainZonesPath)

    mountainZonesRDD.analyze
```
