### ISSUE TITLE
[Important] GeoSpark is Calling For Support

### ISSUE THREAD

**Issue by jiayuasu** [apache/sedona#391]
# Donate open-source GeoSpark to a major OSS foundation. We need help!

Dear GeoSpark contributors and users,

Thank you for your support in the past! We really hope that this software helped you in your work, your company and even your life.  As you all know, GeoSpark in this repository is free of charge and open-source. Any contribution is welcome. In turn, the power of the OSS brings us numerous users and code patches.

Now, we decide to push the GeoSpark project to the next stage. The committers are writing proposals to donate GeoSpark to one of the major Open Source Software foundations. We hope they can accept GeoSpark. This will bring in more users and opportunities to this project. Note that the name of "GeoSpark" might be changed in order to avoid the trademark conflict with Apache Spark.

We have been trying to expose GeoSpark to the public as much as we can:
1. GeoSpark tutorial at ApacheCon North America in September: https://www.apachecon.com/acna19/s/#/scheduledEvent/1117  
2. GeoSpark tutorial at a prestigious Database conference IEEE International Conference on Data Engineering: https://jiayuasu.github.io/geospatial-tutorial/
3. GeoSpark research publications: https://datasystemslab.github.io/GeoSpark/publication/

To complete this proposal, we need to have a couple of users and code contributors to champion this project. I have sent out a couple of emails. However, I still do not have the email addresses of many GeoSpark users and contributors. If you are a GeoSpark code contributor / user but you didn't receive my email, this means I didn't have your email address.

## How to help GeoSpark

We need the following information from GeoSpark users and code contributors

1. Code contributor or user?
2. Full name:
3. Affiliation (company name or university name):
4. Email address:

Here is an example to show how we will use your information in the proposal:

```
Initial code contributors
Jia Yu (Arizona State University, jiayu2@asu.edu)

Initial users
Jia Yu (Arizona State University, jiayu2@asu.edu)
```

# If you are willing to help, please either post your information in this thread or send us an email at your earliest convenience. 

Our contact information is
Jia Yu (Ph.D. student at Arizona State University, jiayu2@asu.edu)
Mohamed Sarwat (Assistant Professor at Arizona State University, msarwat@asu.edu)

Here I am pinging several GeoSpark contributors that I don't have the contact information. @netanel246 @geoHeil @tociek @Serhuela @devlucasc

**Comment by geoHeil** [comment]
I just sent you a reply.

**Comment by sagar1993** [comment]
Code contributor
Full name: Sagar Patni
Arizona State University
Email address: patni.sagar12@gmail.com

**Comment by aocalderon** [comment]
User
Andres Calderon (University of California, Riverside. acald013@ucr.edu)

**Comment by alifiyaali** [comment]
User
full name : Alifiya Pipewala
company name : Innoeye Technologies
email address : alifiyaali28@gmail.com

**Comment by jiayuasu** [comment]
Thank you guys!

**Comment by rishabhzn200** [comment]
Code contributor
Full name: Rishabh Mishra
Arizona State University
Email address: rmishr19@asu.edu

**Comment by lvkrlv** [comment]
1. User
2. Leonid Krylov
3. VimpelCom Ltd.
4. leonidvkrylov@gmail.com

**Comment by fmarchand** [comment]
1. User and maybe contributor (to improve the heatmap :p)
2. Franck MARCHAND
3. Company : Agaetis 
4. fmarchand@agaetis.fr

**Comment by kaushikCanada** [comment]
User
Full Name: Kaushik Roy
kaushik.roy1984@gmail.com

**Comment by tadziqusky** [comment]
User
    Tadeusz Balcer
    tad.balcer@gmail.com

**Comment by jiayuasu** [comment]
Hello everyone in the GeoSpark community, we would like to share the latest update of donating GeoSpark to a major OSS foundation:

## Status

We have submitted a proposal to Apache Incubator under the name "Apache Sedona", which is a city in Arizona (the place where it all started). We are fortunate to have Felix Cheung as the champion of this project. 


We believe the new name won't cause confusion / trademark issues any more in the future and we plan on advertising the new name to all the system users via the GitHub repo. An Apache incubator project, after around one year incubation, if it succeeds, will graduate and become an Apache top level project. You can find the proposal here: https://cwiki.apache.org/confluence/display/INCUBATOR/Sedona+Proposal

## What's next?

In order to get accepted by Apache incubator, Apache Sedona will go through two steps:

1. Discussion: This week, the proposal is under discussion by the members in Apache Software Foundation. You can find the discussion thread here: https://mail-archives.apache.org/mod_mbox/incubator-general/202007.mbox/%3cCALV_acc0FSyi3GNaY25pkjMsO+eYisdL3m0O-YZr_H_jequrSw@mail.gmail.com%3e

2. If we address all the questions raised by the members, the proposal will proceed to the next step, which is the voting step. If the proposal passes the voting, Sedona will be accepted by Apache Incubator and kick start the incubation.

Please stay tuned and we will keep you posted once we get the final result!

**Moreover, all code contributors have been contacted by us previously (via emails) regarding this donation. But if you think we forgot you, please feel free to reach out. We are more than happy to add you. The fact is, we always try our best to include everyone rather than excluding anyone.**

**Comment by jiayuasu** [comment]
# Dear Apache Sedona (formerly GeoSpark) Initial Contributors
@SW186000 @omkarkaptan @avshRepo @Wrussia @scially @imdany @AntonPeniaziev @tociek @strump @sergiimk @semensanyok @sagar1993 @rishabhzn200 @n0mer @lnagel @keivanshahida @jordanperr @eschizoid @davidkell @Zverik @Serhuela @Lancher @JulienPeloton @JLLeitschuh @D0d0 @mrb24 @matb

Sorry for the repeated messages if you receive it multiple times. 

Congratulations! Apache Sedona (formerly GeoSpark) has passed the discussion and voting phases of Apache Incubator and joined Apache Software Foundation open-source projects. It is now under incubation and still open-source. Thank you for your help!

The announcement: https://mail-archives.apache.org/mod_mbox/incubator-general/202007.mbox/%3CCALV_aceT2fz%2BZD8ZzdSurxicKpzLAKK7Zh6eFMRfYkT8LmR6Tw%40mail.gmail.com%3E

The proposal: https://cwiki.apache.org/confluence/display/INCUBATOR/Sedona+Proposal

We are now working on importing Sedona code to ASF and setting up the website, JIRA and mailing list under Apache. Your contribution history is expected to be kept in the Sedona ASF Git repository.

## ACTION REQUIRED

According to the Apache Software Foundation, no releases are possible until the provenance of all the code to be release has been clearly established and the relevant paperwork filed with Apache.

### At your earliest convenience, every contributor please submit your CLA doc to secretary@apache.org using "Apache Sedona (incubating)" as project in your CLA.

This will allow your contribution to be used in Apache Sedona (incubating) (still open-source and under Apache License 2.0). 

### Please find the detailed ASF IP requirements here: http://incubator.apache.org/guides/ip_clearance.html

### Please find the CLA here: http://apache.org/licenses/contributor-agreements.html#clas

### Please reply to this email (jiayu198910@gmail.com) after you submit your CLA to secretary@apache.org

If you are not willing to sign this CLA and not allow us to use your code in Apache Sedona, please let me know. Thank you very much for your collaboration! This means a lot to us!

Regards,
Jia Yu

**Comment by jiayuasu** [comment]
Additional information for the community of Apache Sedona (incubating) transition period,

website, brand, announcements (website comes after source repo change)
http://incubator.apache.org/guides/sites.html
http://incubator.apache.org/guides/press-kit.html
http://incubator.apache.org/guides/publicity.html
http://incubator.apache.org/guides/branding.html

reporting
http://incubator.apache.org/policy/incubation.html#podling_reporting

release
http://incubator.apache.org/policy/incubation.html#disclaimers
http://incubator.apache.org/policy/incubation.html#releases
https://incubator.apache.org/guides/releasemanagement.html#choice_of_disclaimers
https://incubator.apache.org/guides/releasemanagement.html
http://incubator.apache.org/cookbook/#two_phase_vote_on_podling_releases
https://www.apache.org/foundation/voting

community
http://www.apache.org/foundation/mailinglists.html
http://incubator.apache.org/guides/ppmc.html
http://incubator.apache.org/guides/committer.html
http://incubator.apache.org/guides/community.html
http://incubator.apache.org/guides/participation.html
http://incubator.apache.org/guides/roles_and_responsibilities.html
