### ISSUE TITLE
X and Y axes are swapped after CRS transformation of shapefile

### ISSUE THREAD

**Issue by kaushikCanada** [apache/sedona#400]
I am readign a simple shapefile and printing coordinates. whats happenning is that the axes of the corodinates are gettign swapped after crs conversion. thus we are gettign invalid result.
## Expected behavior
val user_file2 = "/Users/royka/roy/webmap-app/resources/CT_Within_3km"
 val shapeRDD2 = ShapefileReader.readToGeometryRDD(spark.sparkContext, user_file2)
var rawSpatialDf2 = Adapter.toDf(shapeRDD2, spark)
  rawSpatialDf2.createOrReplaceTempView("rawSpatialDf2")
  var spatialDf2 = spark.sql("""SELECT **ST_Transform(st_geomFromWKT(geometry),"epsg:3347", "epsg:4326")** as geom

                               FROM rawSpatialDf2
                            """.stripMargin)
spatialDf2.show(false)
[CT_Within_3km.zip](https://github.com/DataSystemsLab/GeoSpark/files/3821150/CT_Within_3km.zip)
Expected behaviour is **POLYGON ((-80.49499887234829 43.51154626748679.**..
## Actual behavior
**POLYGON ((43.51154626654474 -80.49499887234825,..**...
## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.4.0

JRE version = 1.8

API type = Scala or Java? Scala

**Comment by kaushikCanada** [comment]
I also tried using the UseLongitudeLatitudeOrder:Boolean option, but its not working. same results. please help.

**Comment by kaushikCanada** [comment]
any update on this please?

**Comment by SW186000** [comment]
On my laptop, I execute my code and the result is not swapped.

**Comment by gaodq** [comment]
I have the same problem.

**Comment by gaodq** [comment]
It works when add `spark.driver.extraJavaOptions    -Dorg.geotools.referencing.forceXY=true` configuration
