### ISSUE TITLE
Unable to load shape file where the .shp file is considerably larger compared to .shx and .dbf

### ISSUE THREAD

**Issue by cakilandeswari** [apache/sedona#403]
## Expected behavior

Should be able to read shape file successfully.

## Actual behavior
val shapefileInputLocation = "t1"
var postalRDD = ShapefileReader.readToGeometryRDD(spark.sparkContext, shapefileInputLocation)

java.lang.ArrayIndexOutOfBoundsException: 0
  at scala.collection.mutable.WrappedArray$ofRef.apply(WrappedArray.scala:127)
  at scala.collection.convert.Wrappers$SeqWrapper.get(Wrappers.scala:66)
  at org.datasyslab.geospark.formatMapper.shapefileParser.ShapefileReader.readFieldNames(ShapefileReader.java:184)
  at org.datasyslab.geospark.formatMapper.shapefileParser.ShapefileReader.readToGeometryRDD(ShapefileReader.java:79)
  at org.datasyslab.geospark.formatMapper.shapefileParser.ShapefileReader.readToGeometryRDD(ShapefileReader.java:63)
  ... 56 elided

## Steps to reproduce the problem
Shape files cannot be shared. But this is the size of the shape file in bytes.
18684852  t1/t1.dbf
968115780  t1/t1.shp
260508 t1/t1.shx

## Settings

GeoSpark version = 2.3

Apache Spark version = 2.4.1

JRE version = 1.8

API type = Scala 

On debugging, it looks like the code for shape file reader looks only at split(0), but there are in fact two splits where shp is in one split and shx,dbf are in another split.

Is there any setting that is needed for this to work (mapreduce.input.fileinputformat.split.minsize.per.node/mapreduce.input.fileinputformat.split.minsize.per.rack) etc. ?

**Comment by cakilandeswari** [comment]
my crude workaround was to combine all the splits in to one.

--- a/core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/shapes/ShapeInputFormat.java
+++ b/core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/shapes/ShapeInputFormat.java
@@ -16,12 +16,14 @@
  */
 package org.datasyslab.geospark.formatMapper.shapefileParser.shapes;
 
+import org.apache.commons.io.FilenameUtils;
 import org.apache.hadoop.fs.Path;
 import org.apache.hadoop.mapreduce.InputSplit;
 import org.apache.hadoop.mapreduce.JobContext;
 import org.apache.hadoop.mapreduce.RecordReader;
 import org.apache.hadoop.mapreduce.TaskAttemptContext;
 import org.apache.hadoop.mapreduce.lib.input.CombineFileInputFormat;
+import org.apache.hadoop.mapreduce.lib.input.CombineFileSplit;
 
 import java.io.IOException;
 import java.util.ArrayList;
@@ -59,9 +61,46 @@ public class ShapeInputFormat
         List<InputSplit> splits = new ArrayList<>();
         for (int i = 0; i < paths.length; ++i) {
             job.getConfiguration().set("mapred.input.dir", paths[i]);
-            splits.add(super.getSplits(job).get(0));
+            splits.add(getSplit(job));
         }
         return splits;
     }
+
+    private InputSplit getSplit(JobContext job)
+            throws IOException
+    {
+        // get indexes of all .shp file
+        int cnt=0;
+
+        // get original combine split.
+        List<InputSplit> splits = super.getSplits(job);
+        for (InputSplit split: splits) {
+            CombineFileSplit combineSplit = (CombineFileSplit) split;
+            Path[] paths = combineSplit.getPaths();
+            cnt+=paths.length;
+        }
+
+        // prepare parameters for constructing new combine split
+        Path[] shpPaths = new Path[cnt];
+        long[] shpStarts = new long[cnt];
+        long[] shpLengths = new long[cnt];
+
+        int i =0;
+        for (InputSplit split: splits) {
+            CombineFileSplit combineSplit = (CombineFileSplit) split;
+            Path[] paths = combineSplit.getPaths();
+            for (int j = 0; j < paths.length; ++j) {
+                shpPaths[i] = combineSplit.getPath(j);
+                shpStarts[i] = combineSplit.getOffset(j);
+                shpLengths[i] = combineSplit.getLength(j);
+                i++;
+            }
+        }
+
+        //combine all .shp splits as one split.
+        CombineFileSplit combineSplit = (CombineFileSplit) splits.get(0);
+        CombineFileSplit shpSplit = new CombineFileSplit(shpPaths, shpStarts, shpLengths, combineSplit.getLocations());
+        return shpSplit;
+    }
 }

Please advise. Thanks.

**Comment by KoenR3** [comment]
I am facing the same issue
