### ISSUE TITLE
Optimize St_Contains RangeJoin Partitioning

### ISSUE THREAD

**Issue by byang4** [apache/sedona#405]
Trying to Range Join a small set of nonoverlapping multipolygons(64 shapes) with a large set of Points (millions) using the ST_contains and ST_Within functions in GeoSparkSQL. 

## Expected behavior
Joined dataframe is Points + polygon name that the point is contained in. 

## Actual behavior
polygonDf and resultant joined Dataframe are stored in a single partition which causes a shuffle failure or hanging runtime. 

I have attempted both ST_Contains and ST_Within.
ST_Contains(polygons.geometry, points.geometry)
ST_Within(points.geometry, polygons.geometry)

## Steps to reproduce the problem
I am unable to reproduce without the specific polygon dataset. Polygon Dataset is ingested as a multipolygon shapefile. 

## Settings

GeoSpark version = 1.2.0
geospark-sql_2.3

Apache Spark version = 2.4.0

JRE version = 1.8?

API type = Scala

**Comment by jiayuasu** [comment]
@byang4 This is very strange. I actually didn't meet this issue before...

**Comment by geoHeil** [comment]
If you have a small to medium sized data set of POI points and want to enrich a larger one you might be better of with a different approach. https://georgheiler.com/publication/ieee-bigdata-19/ describes a broadcast based spatial join.

And I agree it would be awesome to include this into gespark as an optimization.
But still it is very strange that the code hangs.

**Comment by byang4** [comment]
I've tried broadcasting the smaller dataset the partitions the larger dataset is stored on. Is there anyway to spatially repartition the dataset in GeoSpark DataFrame APIs?

**Comment by geoHeil** [comment]
Why do you need to repartition? A broadcast nicely circumvents this. And instead of only broadcasting the data you could broadcast an R-tree or any other spatial index with it as well.

Or is your intention to store the large and finally enriched data spatially partitioned for further (later) retrieval?

**Comment by byang4** [comment]
No, you are correct, I just planned on aggregating the data afterwards. 

From my understanding, I need to repartition because my initial small polygonDf gets loaded into one partition. It seems Spark was somehow shuffling the larger dataframe to the smaller dataset, which happens to be stored on one partition, leading to the shuffle failure on a single executor. 

In theory, I can see how a broadcast would solve this. If the polygonDf is available on every node, Spark won't shuffle the larger dataset. Is there an example of how to explicitly implement this, because I am unable to get Spark to behave the way I want it to.

**Comment by geoHeil** [comment]
https://github.com/complexity-science-hub/distributed-POI-enrichment

I sent you a link last time for a manual implementation.

Are you sure your first dataframe, I.e. The left side which is spatially
partitioned by default is the large dataframe? As you explain above the
large one is shuffled to the small one - this is definitely not how
geospark usually behaves.

Best
Georg

byang4 <notifications@github.com> schrieb am Di. 17. Dez. 2019 um 05:32:

**Comment by byang4** [comment]
Yes, the record size is in the millions while the smaller is roughly 60. Thank you for your guidance, I will try to implement the broadcast. 

Does the this broadcast not cause a broadcast nested loop join due to the spatial partitioning?

**Comment by geoHeil** [comment]
From a semantic perspective yes. But you could also resort to geohashes /
S2 / H3 if you prefer hashes.
Anyhow this still should be much faster as no distributed partitioning is
required.

byang4 <notifications@github.com> schrieb am Mi. 18. Dez. 2019 um 22:22:

**Comment by tnyz** [comment]
> From a semantic perspective yes. But you could also resort to geohashes / S2 / H3 if you prefer hashes. Anyhow this still should be much faster as no distributed partitioning is required. 

@geoHeil did you notice any performance difference between using geohash and Rtree/quadtree as index in broadcast spatial join?

**Comment by geoHeil** [comment]
I personally sometimes use H2 for its nice neighborhood accessibility when only gridded resolution is enough. I.e. choose more by features instead of performance. I did not perform excessive-performance testing here.
But sometimes, I rely on a broadcasted RTree as it could return the KNN if no direct match is found, i.e. I do not explicitly need to select a neighborhood.

**Comment by tnyz** [comment]
Thanks for you response. My gut tells me that the runtime complexity for using broadcast hash join is O(m) while with Rtree (or any broadcast tree) is O(m*log(n)), so using hashes might be more efficient theoretically in this particular case. Anyway both these implementation is much better than nested loop.
