### ISSUE TITLE
maven jar is a fat jar including geotools

### ISSUE THREAD

**Issue by geoHeil** [apache/sedona#410]
The jar which can be obtained using the standard build tools from maven central is a fat jar. Dependencies are included.

https://github.com/DataSystemsLab/GeoSpark/issues/23 already describes such behavior it still has not been resolved

For example a: `jar -tf /Users/geoheil/Downloads/geospark-1.2.0.jar |grep geotools` results in many:

```
...
org/geotools/data/memory/MemoryFeatureSource.class
org/geotools/data/memory/MemoryFeatureCollection.class
org/geotools/data/memory/MemoryFeatureCollection$MemoryIterator.class
org/geotools/data/memory/MemoryDataStore$1.class
...
```

classes being found.
They should be linked from maven / your build tool of choice, not directly included in the fat jar

**Comment by jiayuasu** [comment]
@geoHeil I intend to package Geotools into GeoSpark. I didn't pack Spark and SparkSQL but all other dependencies are packed. This way, the user does not have to specify a number of other packages in his/her POM.xml, when use GeoSpark.

The issue mentioned in #23 has been solved by me long time ago. The old GeoSpark jar packaged Apache Spark as well.

**Comment by geoHeil** [comment]
ok. Would you mind if I suggest shading these transitive dependencies?

The reason is: by including it in your fat jar, any dependency management tool (standard build tool like maven) no longer can reason about the included dependencies. This is only fine as long as I do not need a different version of one of these on my classpath. For example, I currently face issues regarding geotools.

**Comment by geoHeil** [comment]
Perhaps shading is not the only thing that should be considered.

It should be seen in an effort to make geospark integrate with other geospatial packages such as geomesa https://github.com/DataSystemsLab/GeoSpark/issues/253

As such, there should be an additional which is not a fat jar so that easy integration in other geospatial projects is possible
