### ISSUE TITLE
Geospark-viz contains bundled / non-shaded Amazon AWS SDK

### ISSUE THREAD

**Issue by kervel** [apache/sedona#412]
## Expected behavior

I'd like to combine geospark (1.2.0 for spark 2.3) with other packages that use data from amazon S3. I would expect it to just work

## Actual behavior
When doing spark.read.format("s3a://") in my project it fails with

Uncaught exception: com.amazonaws.http.AmazonHttpClient.disableStrictHostnameVerification()V (java.lang.NoSuchMethodError)

removing the geospark-viz dependency solves the problem

When looking in the geospark-viz_2.3-1.2.0.jar i got from maven central, i find a copy of the amazon S3 SDK in it:
```
root@polynote-fdfdf458-pt94m:~/.cache# unzip -l geospark-viz_2.3-1.2.0.jar | grep -i AmazonHttp
    15341  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient.class
     4425  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient$RequestExecutionBuilderImpl.class
     2014  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient$Builder.class
    42469  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient$RequestExecutor.class
     6061  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient$RequestExecutor$ExecOneRequestParams.class
     1311  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient$RequestExecutionBuilder.class
     1157  2019-03-04 02:10   com/amazonaws/http/AmazonHttpClient$1.class
```

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.4

JRE version = 1.8

API type = Scala 2.11

**Comment by jiayuasu** [comment]
@kervel I believe you can use "exclude" function in Maven or SBT to exclude this amazon s3 jar.

**Comment by jiayuasu** [comment]
@kervel If you want to use GeoSparkViz but want to use your own AWS sdk, you can exclude https://github.com/DataSystemsLab/GeoSpark/blob/master/viz/pom.xml#L70 this dependency in your pom or sbt.
