### ISSUE TITLE
ST_GeomFromWkt and ST_GeomFromText converts multipolygon to polygon

### ISSUE THREAD

**Issue by Debadarsini** [apache/sedona#424]
## Expected behavior
A multipolygon should be converted to multipolygon not polygon when ST_GeomFromWkt and ST_GeomFromText functions applied.

## Actual behavior
MULTIPOLYGON (((-97.143362 27.84948, -97.14051 27.849375, -97.13742 27.849375, -97.13647 27.851056, -97.136945 27.853788, -97.138728 27.855784, -97.141223 27.853158, -97.143362 27.84948)), 
((-97.131954 27.894443, -97.131716 27.896018, -97.1212014 27.8937854, -97.113415 27.892132, -97.110206 27.890662, -97.110206 27.889191, -97.1104204 27.8890963, -97.112107 27.888351, -97.114247 27.886985, -97.11591 27.88583, -97.11698 27.885515, -97.1173397 27.8855439, -97.118287 27.88562, -97.1180218 27.8875761, -97.117931 27.888246, -97.118287 27.890662, -97.1187136 27.8907652, -97.125269 27.8923509, -97.129577 27.893393, -97.131954 27.894443)), ((-97.150493 27.874905, -97.150849 27.875851, -97.149067 27.877531, -97.146927 27.878267, -97.14467 27.880893, -97.143362 27.881523, -97.142055 27.881103, -97.14158 27.879527, -97.142412 27.878582, -97.143719 27.878372, -97.145383 27.876586, -97.147403 27.875641, -97.149423 27.874905, -97.150493 27.874905)), ((-97.277888 27.915016, -97.280673 27.916797, -97.277151 27.918885, -97.270902 27.924911, -97.268651 27.926005, -97.269181 27.927081, -97.266121 27.927604, -97.257 27.927545, -97.231476 27.927514, -97.230477 27.953057, -97.229337 27.954497, -97.227041 27.955697, -97.226871 27.956842, -97.227509 27.984419, -97.240412 27.991214, -97.249501 27.99119, -97.249808 28.00156, -97.249403 28.008394, -97.249352 28.015777, -97.246465 28.020607, -97.217976 28.006301, -97.214474 28.011763, -97.187227 27.974459, -97.185218 27.975922, -97.18445 27.978007, -97.18181 27.979354, -97.181351 27.980691, -97.179325 27.979937, -97.177906 27.981857, -97.180899 27.981241, -97.180019 27.983282, -97.177081 27.985091, -97.177068 27.987313, -97.175036 27.98849, -97.174192 27.991763, -97.175233 27.993887, -97.173479 27.996164, -97.170119 27.997582, -97.168713 27.996343, -97.165283 27.992159, -97.10562 27.956867, -97.098551 27.965841, -97.099903 27.963404, -97.095463 27.960391, -97.094531 27.960663, -97.095924 27.961514, -97.093476 27.964801, -97.096948 27.967277, -97.092467 27.964277, -97.093252 27.964707, -97.095581 27.961632, -97.0942561 27.9607887, -97.120902 27.923113, -97.129276 27.918726, -97.131359 27.916602, -97.131241 27.914922, -97.129933 27.912192, -97.131359 27.907046, -97.132342 27.905581, -97.133023 27.90253, -97.1338567 27.9011057, -97.136312 27.90439, -97.137131 27.902861, -97.138515 27.900826, -97.136995 27.899203, -97.13535 27.8978363, -97.135638 27.896964, -97.135671 27.896907, -97.1375368 27.8936862, -97.138133 27.892657, -97.141342 27.88667, -97.144432 27.883099, -97.147641 27.88646, -97.148829 27.8852, -97.1490339 27.884976, -97.151396 27.882393, -97.154652 27.876796, -97.1546812 27.8767587, -97.154642 27.877004, -97.161216 27.880646, -97.161268 27.880676, -97.162722 27.881532, -97.163644 27.882081, -97.164889 27.880906, -97.166941 27.879639, -97.170125 27.881547, -97.16912 27.882906, -97.167873 27.884568, -97.170064 27.885862, -97.181393 27.892565, -97.183688 27.889517, -97.197275 27.89754, -97.195021 27.900546, -97.197251 27.902384, -97.200396 27.906587, -97.195212 27.91354, -97.203996 27.913649, -97.20666 27.919866, -97.21019 27.918115, -97.217076 27.915506, -97.223506 27.912777, -97.220665 27.90783, -97.232103 27.908176, -97.232165 27.90647, -97.233391 27.906212, -97.233185 27.892319, -97.233476 27.89176, -97.234908 27.892503, -97.248829 27.899804, -97.277888 27.915016)))

POLYGON ((-97.143362 27.84948, -97.14051 27.849375, -97.13742 27.849375, -97.13647 27.851056, -97.136945 27.853788, -97.138728 27.855784, -97.141223 27.853158, -97.143362 27.84948), x(-97.131954 27.894443, -97.131716 27.896018, -97.1212014 27.8937854, -97.113415 27.892132, -97.110206 27.890662, -97.110206 27.889191, -97.1104204 27.8890963, -97.112107 27.888351, -97.114247 27.886985, -97.11591 27.88583, -97.11698 27.885515, -97.1173397 27.8855439, -97.118287 27.88562, -97.1180218 27.8875761, -97.117931 27.888246, -97.118287 27.890662, -97.1187136 27.8907652, -97.125269 27.8923509, -97.129577 27.893393, -97.131954 27.894443), (-97.150493 27.874905, -97.150849 27.875851, -97.149067 27.877531, -97.146927 27.878267, -97.14467 27.880893, -97.143362 27.881523, -97.142055 27.881103, -97.14158 27.879527, -97.142412 27.878582, -97.143719 27.878372, -97.145383 27.876586, -97.147403 27.875641, -97.149423 27.874905, -97.150493 27.874905), (-97.277888 27.915016, -97.280673 27.916797, -97.277151 27.918885, -97.270902 27.924911, -97.268651 27.926005, -97.269181 27.927081, -97.266121 27.927604, -97.257 27.927545, -97.231476 27.927514, -97.230477 27.953057, -97.229337 27.954497, -97.227041 27.955697, -97.226871 27.956842, -97.227509 27.984419, -97.240412 27.991214, -97.249501 27.99119, -97.249808 28.00156, -97.249403 28.008394, -97.249352 28.015777, -97.246465 28.020607, -97.217976 28.006301, -97.214474 28.011763, -97.187227 27.974459, -97.185218 27.975922, -97.18445 27.978007, -97.18181 27.979354, -97.181351 27.980691, -97.179325 27.979937, -97.177906 27.981857, -97.180899 27.981241, -97.180019 27.983282, -97.177081 27.985091, -97.177068 27.987313, -97.175036 27.98849, -97.174192 27.991763, -97.175233 27.993887, -97.173479 27.996164, -97.170119 27.997582, -97.168713 27.996343, -97.165283 27.992159, -97.10562 27.956867, -97.098551 27.965841, -97.099903 27.963404, -97.095463 27.960391, -97.094531 27.960663, -97.095924 27.961514, -97.093476 27.964801, -97.096948 27.967277, -97.092467 27.964277, -97.093252 27.964707, -97.095581 27.961632, -97.0942561 27.9607887, -97.120902 27.923113, -97.129276 27.918726, -97.131359 27.916602, -97.131241 27.914922, -97.129933 27.912192, -97.131359 27.907046, -97.132342 27.905581, -97.133023 27.90253, -97.1338567 27.9011057, -97.136312 27.90439, -97.137131 27.902861, -97.138515 27.900826, -97.136995 27.899203, -97.13535 27.8978363, -97.135638 27.896964, -97.135671 27.896907, -97.1375368 27.8936862, -97.138133 27.892657, -97.141342 27.88667, -97.144432 27.883099, -97.147641 27.88646, -97.148829 27.8852, -97.1490339 27.884976, -97.151396 27.882393, -97.154652 27.876796, -97.1546812 27.8767587, -97.154642 27.877004, -97.161216 27.880646, -97.161268 27.880676, -97.162722 27.881532, -97.163644 27.882081, -97.164889 27.880906, -97.166941 27.879639, -97.170125 27.881547, -97.16912 27.882906, -97.167873 27.884568, -97.170064 27.885862, -97.181393 27.892565, -97.183688 27.889517, -97.197275 27.89754, -97.195021 27.900546, -97.197251 27.902384, -97.200396 27.906587, -97.195212 27.91354, -97.203996 27.913649, -97.20666 27.919866, -97.21019 27.918115, -97.217076 27.915506, -97.223506 27.912777, -97.220665 27.90783, -97.232103 27.908176, -97.232165 27.90647, -97.233391 27.906212, -97.233185 27.892319, -97.233476 27.89176, -97.234908 27.892503, -97.248829 27.899804, -97.277888 27.915016))

Above multipolygon is converted to polygon geometry.

## Steps to reproduce the problem

Use above multipolygon to convert using ST_GeomFromWkt and ST_GeomFromText and it results in a polygon

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.2

JRE version = 1.8?

API type = Scala or Java?

**Comment by netanel246** [comment]
Hi,
I've found the reason. 
The function `getType` in `org.datasyslab.geospark.formatMapper.shapefileParser.parseUtils.shp`,
not support with multipolygon or multilinestring:

> public static ShapeType getType(int id)
>     {
>         ShapeType type;
>         switch (id) {
>             case 1:
>                 type = POINT;
>                 break;
>             case 3:
>                 type = POLYLINE;
>                 break;
>             case 5:
>                 type = POLYGON;
>                 break;
>             case 8:
>                 type = MULTIPOINT;
>                 break;
>             default:
>                 type = UNDEFINED;
>         }
>         return type;
>     }
> 

@jiayuasu there is a reason why it's not implemented?

**Comment by jiayuasu** [comment]
@netanel246 There is no particular reason for it. Most likely, @zongsizhang forgot to handle all sorts of geometry types.

@netanel246  Do you want to help solve this?

**Comment by netanel246** [comment]
Yes. I will try.

**Comment by netanel246** [comment]
@zongsizhang, @jiayuasu 
I saw that geotools already have a [shapeFileReader](https://github.com/geotools/geotools/tree/master/modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp)
that already handle all the shape types(including multipolygon, m values etc.), and it's already a dependency.
There is a reason why geospark don't use it?

**Comment by jiayuasu** [comment]
@netanel246 

1. The shapefile reader in GeoSpark is different from that in GeoTools.

Our shapefile reader will be able to read shapefiles that are stored in distributed storage such as HDFS and automatically partition it to an RDD. Please look at this line: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/ShapefileReader.java#L101 We extend the newAPIHadoopFile

You may use GeoTools to handle multi-polygon or other spatial data types when our shapfile reader identifies new spatial objects.

2. What do you mean: "why geospark need to go through the shapefile reader when reading a WKT"?

**Comment by jiayuasu** [comment]
@netanel246 Regarding the problem in this issue, I don't think  ST_GeomFromWkt is using any code in Shapefile reader. Instead, it uses the WKT reader from JTS, internally.

**Comment by Debadarsini** [comment]
Those deserializer need to be fixed.
For the time being i am using below code as udf to unblock myself
             val wktr:WKTReader = new WKTReader();
             val leftwkt:Geometry = wktr.read(leftgeo)
             val rightwkt:Geometry = wktr.read(rightgeo)
              leftwkt.covers(rightwkt)

**Comment by netanel246** [comment]
@jiayuasu 
That's not what I see when I was debugging to solve the issue.
`ST_GeomFromWkt` calls the function `deserialize` on `package org.datasyslab.geosparksql.utils`,
in this function there is a line:
`    val geometry = geometrySerde.read(kryo, input, classOf[Geometry])`
and this one call:
```
switch (geometryType) {
            case SHAPE:
                return readGeometry(kryo, input);
```
While readGeometry definition:

```
private Geometry readGeometry(Kryo kryo, Input input)
    {
        Geometry geometry = ShapeSerde.deserialize(input, geometryFactory);
        geometry.setUserData(readUserData(kryo, input));
        return geometry;
    }
```
 As you can see, this function use ShapeSerde that parse the input as a shapefile.
That's why I end up to fix the ShapeReader, which will support MultiLineString and MultiPolygon.

**Comment by netanel246** [comment]
@jiayuasu as @Debadarsini The ST_GeomFromWkt actually use the ShapeSerde, hence, multipolygon and multilinestring are not handled well.
We need to fix that.
Besides that, we need to extend the ShapeFileSerde capabilities to support those types along with z value and m value.
What do you think about that?

**Comment by Debadarsini** [comment]
@netanel246  Yes fixing deserializer code the best solution. Thank you for working on it.

**Comment by jiayuasu** [comment]
@netanel246 
(1) Yes, please fix the multipolygon and multilinestring porblem in the ShapeSerde if you have time. A simple way to fix it is to use WKB writer to write spatial objects to binary objects, rather than use ShapefileReader

(2)  Well, you can solve the z value and m value issue but GeoSpark does not support Z and M value anyway.

**Comment by Debadarsini** [comment]
@netanel246  To unblock myself i wrote ST_Covers 
https://github.com/Debadarsini/geospark-st-covers/blob/8fa31faa8c4c62704dee44ddfcd9bbe6c8c73d53/sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Predicates.scala#L88
