### ISSUE TITLE
Encoding not working on GCP DataProc

### ISSUE THREAD

**Issue by haneemedhat** [apache/sedona#425]
## Expected behavior
I'm running a GeoSpark Scala job on GCP Dataproc cluster and I'm reading a map shapefile that contains special characters and added the property for setting encoding to UTF8 as described in the documentation, then converting it to a Dataframe.

It is expected when printing the data or saving it into CSV it should show the special characters normally. 

## Actual behavior
As described above, it doesn't show the normal special characters but shows malformed characters.

Noting that I ran the same job in local environment on same shapefile but it prints the characters correctly. 

## Steps to reproduce the problem
Here is a sample code that I use in the job.
```
  System.setProperty("geospark.global.charset", "utf8")
  System.setProperty("org.geotools.referencing.forceXY", "true")

  println("Encoding Property: " + System.getProperty("geospark.global.charset"))
  println("Reading the RDD")
  val shape_rdd  = ShapefileReader.readToGeometryRDD(session.sparkContext,inputPath)

  println("Converting the RDD to DF")
  var joinResultDf = Adapter.toDf(shape_rdd, session)
  println("Printing Sample from DF")
  joinResultDf.show(20)

```

## Settings

GeoSpark version = 1.2

Apache Spark version = 2.3

JRE version = 1.8

API type = Scala

**Comment by pedromorfeu** [comment]
Is there any workaround? Maybe setting the property `org.geotools.referencing.forceXY` in every node and not just in the driver?

**Comment by netanel246** [comment]
This one happened to me on Azure on Databricks too with python (I didn't test with scala)
