### ISSUE TITLE
Error in ST_Contains

### ISSUE THREAD

**Issue by mohitgoyal201617** [apache/sedona#429]
##  Expected behavior

celllocgeomvoronoi
root
 |-- polygeom: geometry (nullable = false)

celllocgeom
root
 
 |-- Center_Longitude: double (nullable = true)
 |-- Center_Latitude: double (nullable = true)
 |-- geom: geometry (nullable = false)
 
 
 
 val celllocgeomvornoipolygon=spark.sql("select * from celllocgeom,celllocgeomvoronoi where ST_Contains(celllocgeomvoronoi.polygeom, celllocgeom.geom)")

Getting below error
 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000004477ee5, pid=11780, tid=0x00000000000052b8

 JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode windows-amd64 compressed oops)

## Settings

GeoSpark version = 1.2.0

Apache Spark version =2.1.0

JRE version = 1.8?

API type = Scala or Java? Scala

**Comment by jiayuasu** [comment]
I don't thin this error is caused by GeoSpark
