### ISSUE TITLE
KNNQuery for two PointRDD

### ISSUE THREAD

**Issue by Tsarazin** [apache/sedona#43]
Could you make a KNNQuery function which would take two PointRDD in parameters and would do a basic KNNQuery for every points of one RDD with the other PointRDD?
For the moment we can only do a KNNQuery between one point and one PointRDD. I would like to do the same operation with a lot of Points on the same PointRDD. For every point of the first PointRDD I want to find the KNN points from the second PointRDD. I can do a loop of course but I would like to find a optimal way to do it because I am dealing with big datas.

**Comment by jiayuasu** [comment]
Hi @Tsarazin ,

Thanks for this suggestion. We will find a proper KNN join algorithm and add it into GeoSpark soon.

Thanks,
Jia
