### ISSUE TITLE
Extract X / Y Values from geometry UDT

### ISSUE THREAD

**Issue by iamnckblr** [apache/sedona#430]
## Expected behavior
I exepct I can extract the x and y coordinates from a spark dataframe like this:
`df.select($"point.x as X", $"point.y as Y")`
## Actual behavior
I cannot extract the values
## Steps to reproduce the problem
-
## Settings
-
GeoSpark version = 1.3.1

Apache Spark version = 2.3

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
To me, this does not seem to follow the SQL syntax. So there is no way to support the usage like this. But we can definitely have some UDF functions such as ST_X() and ST_Y()
