### ISSUE TITLE
Seeking Advice: a large number of point in polygon judgment(100 billion points and 1 million polygons) 

### ISSUE THREAD

**Issue by Hank-Yan** [apache/sedona#432]
I have about 80-100 billion points  and about 100 thousand(maximum num is 1 million) simple polygons, my work is to find the points in the polygons. 

currently I use hive and hive streaming to do that thing, and it takes a long time (about 10-13 hours).

I am looking for a new way to do the same thing but use less time, want to konw if geospark can help me, please help me, thanks very much!!!

**Comment by geoHeil** [comment]
Would you mind being more specific what you are doing in hive, which kind of spatial operations you are performing, what the underpinning foundation of your existing geospatial functions in hive is and especially calrify streaming.

**Comment by Hank-Yan** [comment]
@geoHeil  Hi geoHeil， my  spatial operation  just as  "ST_Intersects"  in geospark (ST_Intersects( points,   polygons)).   

In hive， I  read the total points (80-100 billion points),  and use  "Hive Python Streaming"  to map each point  to a polygon,  this map operation is  using a python file,  the python file will load the polygon file  which  has be pretreated (grided) and then check points  one by one.    The core code in the python file  is a function named in_polygon which  is coded by myself.         

I have  learnd  the quick start of geosaprk,   and finished the tutorial of Spatial SQL in Python,  I know how to use ST_Intersects  with the sample data,  but not sure if it is ok in the  large-scale data.   

In  hive , I load pretreated polygon in memory,  and cheking  points  on every mapper.    but I  do not konw the inside principle of geospark。  if it is ok  to process such a  super  massive data sets?

looking forward to your reply，  thanks very much.

**Comment by geoHeil** [comment]
Did you already try to use: https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Documentation and work within the JVM only? this might already speed things up. Are you using spatial indices?

Have you started experimenting with larger datasets already? In general, indeed it is fine to process such large data sets in geospark. The important point is: the data points must not all overlap, otherwise the parallelism obtained by spatially partitioning the data does hot really work in your favor.

**Comment by Hank-Yan** [comment]
Thanks very very much geoHeil !!!  
The spatial-framework-for-hadoop is very useful.  The only problem is that udf  can only process one polygon and one point  a time.    I use some way like spatial indices  by  "Hive Python Streaming" to accelerate my work.   But it is still very useful , I can use so many udfs in other Scenes. 

On the other hand，I  have started experimenting with larger datasets.  When there is a conclusion, I will give a feedback as soon as possible. Thank you so much~

**Comment by geoHeil** [comment]
https://georgheiler.com/publication/ieee-bigdata-19/ 
might be useful for you as long as the smaller data set fits into memory - you can also broadcast the spatial index
