### ISSUE TITLE
Add support to store and received Z values

### ISSUE THREAD

**Issue by netanel246** [apache/sedona#435]
## Expected behavior
Given geometries with Z values, we can store and retrieve them.
## Actual behavior
Z value is not stored, and instead coordinate contains NaN 
## Steps to reproduce the problem
The problem occurs with GeoJSON and Shapefile:

**1. GEOJSON:**
Given geojson file with Z values:
`{ "type": "Feature", "properties": { "STATEFP": "01", "COUNTYFP": "073", "TRACTCE": "004000", "BLKGRPCE": "2", "AFFGEOID": "1500000US010730040002", "GEOID": "010730040002", "NAME": "2", "LSAD": "BG", "ALAND": 344082, "AWATER": 0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -86.855276, 33.492097, 15.0 ], [ -86.851953, 33.494234, 20.0 ], [ -86.848754, 33.496102, 14.0 ], [ -86.846142, 33.493001, 5.0 ], [ -86.853724, 33.488135, 4.0 ], [ -86.853718, 33.490394, 8.0 ], [ -86.855276, 33.492097, 40.0 ] ] ] } },`

`var spatialRDD = GeoJsonReader.readToGeometryRDD(sparkSession.sparkContext, geojsonInputLocation)
println(spatialRDD.getRawSpatialRDD().first().getCoordinates.mkString)` 

**2. SHAPEFILE:**
Reading shapefile with Z value returns empty rawSpatialRDD

## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.5

JRE version = 1.8? yes

API type = Scala or Java? **Scala and Python**

**Comment by netanel246** [comment]
I found that **jts2geojson** are supporting z values after version 0.14.3
I tried to update the package but they using a new version of JTS which updates the JTS package path(locationtech instead of vividsolutions).
@jiayuasu , Can we upgrade JTSPlus to use this newer version in order to make it work?

**Comment by geoHeil** [comment]
@netanel246 FYI https://github.com/DataSystemsLab/GeoSpark/issues/233

**Comment by jiayuasu** [comment]
@netanel246 I am totally fine with upgrading JTSplus to any newer version of JTS. But before that, we need to merge the new functions in JTSplus to JTS main repo. This takes time. Do you want to take over this task?

**Comment by netanel246** [comment]
@jiayuasu, it's not a simpler solution to merge the new version of JTS into JTSPlus?

**Comment by jiayuasu** [comment]
@netanel246 That is a good idea. Although it is not perfect, it can still fix many issue we have right now. The latest version of JTS is 1.16.1. JTSplus is based on 1.14 core. Do you want to bring the missing functions JTSplus?

You can try to directly copy JTS 1.16.1 core code to JTSplus and use Git to study the difference. 

The path name in JTSplus might need to be changed to under location tech.

**Comment by geoHeil** [comment]
I think @netanel246 that this is not a good solution as the future of GIS will no longer use the vivid solutions but rather the location tech namespace.  This would ease interoperability with other tools. But I understand it could be a valid quickfix - but potentially one which is hard to maintain.

**Comment by netanel246** [comment]
@geoHeil, I didn't understand. The changes to JTS Plus **will include** the transform to location tech. The main problem I see is that it's hard to maintain

**Comment by geoHeil** [comment]
Sorry - then I misunderstood your intentions. I think then it could be a good first step towards a pull request.

**Comment by netanel246** [comment]
@jiayuasu 
After reading the code on JTS Plus I decided it will be better to try to merge the new functions in JTS Plus into JTS. I hope to update you soon.
