### ISSUE TITLE
Deploy geospark to Maven Central with scala version 2.12

### ISSUE THREAD

**Issue by celadari** [apache/sedona#438]
## Expected behavior
GeoSpark is currently working/compiling on scala 2.12 (branch 2.4.5) and working.
It would be great for external projects depending on geospark in version 2.12 to download .jar from MavenCentral.

## Actual behavior
Unfortunately, package with scala 2.12 is not available through Maven Repository.

## Settings

GeoSpark version = [1.1-1.3.1]

Apache Spark version = 2.4.5

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
GeoSpark 1.4.0 will support Spark 3.0 and be compiled by Scala 2.12 by default.

**Comment by jornfranke** [comment]
would it be possible to have also for Spark 2.x a 2.12 version? From my experience this can be achieved by enabling crossCompile in the built sbt and then use sbt +clean +publishSigned to publish both version two Maven central.
Normally no big code changes or code changes at all are needed
