### ISSUE TITLE
Python API ShapefileReader returning an empty RDD

### ISSUE THREAD

**Issue by nicolas-renard** [apache/sedona#442]
## Expected behavior
Returning a non empty RDD
## Actual behavior
Hello,

Trying to load a shp into a GeoSpark DataFrame and following the documentation, I used th Python core API ShapeFile Reader before converting it to a DataFrame with the Adapter.toDf method.

For some shapefiles, it works fine, but for others ShapefileReader.readToGeometryRDD actually return an empty RDD. The columns names are present and I can print the Schema (after having converted it to a dataframe), but srdd.countWithoutDuplicates() returns 0.
I can open the not working shapefile with geopandas just fine and the geometry type is shapely.geometry.polygon.Polygon.
Once I have opened it with geopandas, I can convert it to a geospark dataframe, but I'd like to be able to open it directly with GeoSpark if possible.
## Steps to reproduce the problem
```

import os

from pyspark.sql import SparkSession
from geospark.register import GeoSparkRegistrator
from geospark.core.formatMapper.shapefileParser import ShapefileReader
from geospark.register import upload_jars

upload_jars()

spark = SparkSession.builder.appName("test3")\
    .getOrCreate()

GeoSparkRegistrator.registerAll(spark)

srdd = ShapefileReader.\
   readToPointRDD(spark.sparkContext, f"hdfs://{hdfs_ip}:{hdfs_port}/shp_file/")
```

Unfortunately, I can't share the data since it's confidential, but do you have any insights into  what might cause such an issue ?
## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4

JRE version = 1.8

API type = Python

**Comment by nicolas-renard** [comment]
Hello,

Moving forward with the issue, there are a few points I'd like to mention concerning the data (I'm not extensively familiar with GIS data, so apologies in advance for some inaccuracies) :

- When opening in geopandas the shapefile (the one not working in geospark), the geometry is of type `POLYGON Z ((...))`. The data is apparently suppposed to be a MultiPolygone 3D 

- When I transform this geopandas dataframe to a spark one using a `spark.createDataFrame(gdf)`, I notice after a `show()` that GeoSpark displays now displays the geometry as `POLYGON ((...))`

- When I transform the geometry of the geopandas dataframe to WKT (wkt being `POLYGON Z ((...))` ) before writting it on disk in parquet to try to load in directly in a spark dataframe and convert the geometry using `ST_GeomFromWKT`, I get a `java.lang.NullPointerException`

So I'm starting to suspect that `POLYGON Z ((...))` is not the same type as `POLYGON ((...))` and that maybe GeoSpark is not compatible with it. I am correct ?

Moreover, I'd really like to avoid going with the geopandas opening before converting it to a geospark dataframe using `spark.createDataFrame(gdf)` since this operation is quite slow (~50min for 4 million lines), I guess because of serialization and deserialization operations between python and the jvm. And unless I'm mistaken, it's not possible to optimize this operation using Arrow (`.config("spark.sql.execution.arrow.enabled", "true")`) because the geometry type is not compatible.

Any advices / ideas ?

Best regards,

**Comment by Imbruced** [comment]
Hi,
Thats correct, GeoSpark does not support Z values for geometries. Polygon Z and Polygon are not the same beacuse Z means 3rd dimension. It is related to issue #435. I do not know what current status is. Possible fix is to add forcing 2D while reading the data in geospark core code but I do not know how much time it can take.

**Comment by nicolas-renard** [comment]
Hi @Imbruced ,

Thx for you answer.

So when doing a `spark.createDataFrame(gdf)` with gdf having a 3D geometry, It's currently forcing the conversion to 2D automatically ?

> Possible fix is to add forcing 2D while reading the data in geospark core code but I do not know how much time it can take.

Not sure I understood properly : is there currently an option I'm not aware of to force the 2D conversion in the Python core API using ShapefileReader or would it still have to be implemented ?

Plus, could be a nice improvement to have an error returned in case of not compatible geometry data using the ShapefileReader :) (and a warning of some sort if the data is converted in 2D)

Best regards

**Comment by Imbruced** [comment]
Unfortunately it is not possible to do the conversion right now. 
I think geopandas or fiona (geopandas using fiona to loads the data) itself converts the geometry from 3D to 2D, can you check how your wkt string looks like when you have geopandas frame, it has Z in the name (PolygonZ) ?

You have to remember that shapefile is one file itself, using GeoSpark you have to load it on one node and then repartition over your network.

My tip for now, use geopandas to save the data on disk (you can repartition your data during that process) and then load it using GeoSpark SpatialRDD readers.

@jiayuasu 
I can fix the issue with 3rd dimension.

**Comment by nicolas-renard** [comment]
Geopandas read it as a PolygonZ, so it doesn't convert the geometry to 2D. It's propably in the process of transforming it to Geospark with the sql API.

Yes, my thought also : using the old shapely to_wkt() method, it appears to convert it to 2D. I'll go with that.

Thx
