### ISSUE TITLE
Visualization Raster Image as GeoTiff

### ISSUE THREAD

**Issue by flashpixx** [apache/sedona#453]
Hello,

I'm just using GeoSpark at my first project. I'm creating raster images from large datasets, based on that I'm using [GeoServer](http://geoserver.org/) for visualization (and also other tools). But all tools have got support for [GeoTiff](https://en.wikipedia.org/wiki/GeoTIFF) but on [GeoSpark Vis Image Component](https://github.com/DataSystemsLab/GeoSpark/blob/master/viz/src/main/java/org/datasyslab/geosparkviz/utils/ImageType.java#L30-L43) there is no support for a GeoTiff.

So my feature request is, can you add support for GeoTiff with compression? Thanks a lot for that

**Comment by jiayuasu** [comment]
@flashpixx Thanks for this!

**Comment by flashpixx** [comment]
An additional comment for that based on the [ArcGIS Raster Pyramid](https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/raster-pyramids.htm) structure, in a GeoTiff there can be different resolution of the same geographical structure, so this is needed for the tilemaps / zooming process on visualization.

I'm calling the `ST_Render` multiple times but it could be nice, that all data are stored inside a single GeoTiff image
