### ISSUE TITLE
ST_GeomFromGeoJSON parsing looks incorrect

### ISSUE THREAD

**Issue by JacekTokar** [apache/sedona#478]
## Expected behavior
https://gist.github.com/JacekTokar/c4db2f4aec7d5f6ae0df689773b8faac
## Actual behavior
https://gist.github.com/JacekTokar/0e73751c711298fbb18725a3e2ccabb8
## Steps to reproduce the problem
Source GeoJson:
https://gist.github.com/JacekTokar/f2903abddc67d007e1f8047cf59c5463
## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.3

JRE version = 1.8

API type = Scala

Hi,

It looks like ST_GeomFromGeoJSON function is not doing great job when parsing geojson. The example provided here shows that instead of holes, there are additional polygons (filled) on top of "master" polygon). 

This is how it should look like: (JSON converted to WKT using python's geojson+shape
![image](https://user-images.githubusercontent.com/52698180/89660429-9e128600-d8d1-11ea-957b-700ad7eae1e2.png)

This is WKT representation from geospark:
![image](https://user-images.githubusercontent.com/52698180/89660620-e03bc780-d8d1-11ea-986c-4eff62106ad5.png)

Screenshots from https://maththinking.com/gisvisualizer/

I have already workaround for this (using aforementioned python), but hopefully this can be fixed in geospark as well.

Regards
Jacek

**Comment by Imbruced** [comment]
I will look on that today, but is guess it is related to ccw, cw of the polygons.

**Comment by Imbruced** [comment]
Actually there is an issue within your data. According to OGC standard any internal ring (wholes) should be defined as cw linear ring. All your data is defined as ccw linear rings. Please look also on result using ST_GeomFromText Postgis function. 
![image](https://user-images.githubusercontent.com/22958216/90340380-06f7ad80-dff8-11ea-96d0-bd4142578831.png)

I think in geojson+shape approach is a bug. Also shapely has also similar issue.
