### ISSUE TITLE
ST_MakeValid drops significant amount of information

### ISSUE THREAD

**Issue by JacekTokar** [apache/sedona#479]
## Expected behavior
ST_MakeValid should not be dropping information from invalid multipolygons
## Actual behavior
ST_MakeValid executed on geometry generated from https://gist.github.com/JacekTokar/0e73751c711298fbb18725a3e2ccabb8 drops the biggest polygon. 
Output after execution on that Multipolygon:
![image](https://user-images.githubusercontent.com/52698180/89661691-4b39ce00-d8d3-11ea-9c38-8c5a1ab7d8ae.png)

## Steps to reproduce the problem
Execute ST_MakeValid on https://gist.github.com/JacekTokar/0e73751c711298fbb18725a3e2ccabb8
## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.3

JRE version = 1.8

API type = Scala

Quite surprisingly, ST_MakeValid is dropping polygon with the biggest area.

**Comment by Imbruced** [comment]
That's strange but in code I can see JTS.makeValid so perhaps JTS lib did not handle that case well. I checked and old trick also worked with your data. Please try to use ST_Buffer(geom, 0) with your data.

**Comment by JacekTokar** [comment]
Hmm interesting 😄  Will try it soon and report back
