### ISSUE TITLE
Cannot import road network data from Shapefile or GeoJSON as SpatialRDD

### ISSUE THREAD

**Issue by elfprince13** [apache/sedona#481]
## Expected behavior
I would like to import vector data to create a SpatialRDD from standard formats.

## Actual behavior
I have a dataset which I can import into JOSM in multiple formats (and inspect/process with `ogrinfo` and `ogr2ogr`) but cannot use to create a SpatialRDD through the Scala API.

## Steps to reproduce the problem
I downloaded the VT transit dataset from [The National Map](https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/Tran/Shape/), and unzipped and tried the following steps to obtain a working `SpatialRDD`:
 1. `ShapefileReader.readToGeometryRDD(sparkContext, "/Users/thomas/Downloads/Shape/Trans_RoadSegment")`
 2. `ShapefileReader.readToGeometryRDD(sparkContext, "/Users/thomas/Downloads/Shape/Trans_RoadSegment.shp")`
 3. Moving only the files prefixed with `Trans_RoadSegment` into their own directory, also named `Trans_RoadSegment`, and repeating (1)
 4. Convert to `vt_roads.geojson` with `ogr2ogr -f GeoJSON  ~/Downloads/Shape/vt_roads/vt_roads.geojson ~/Downloads/Shape/Trans_RoadSegment/Trans_RoadSegment.shp`, and try to load with `GeoJsonReader.readToGeometryRDD(sparkContext, "/Users/thomas/Downloads/Shape/vt_roads/vt_roads.geojson")`

With (3) only, I am able to access the fieldnames with `spatialRDD.fieldNames` after loading, but in all cases, calling `spatialRDD.analyze` results in a null boundary envelope.

## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.0

JRE version = 1.8

API type = Scala or Java? Scala

**Comment by netanel246** [comment]
1. I took the shape dir and the rdd is empty. I need to dig more about it.

2. You can still read it as a geojson, but only a row JSON, which means one full JSON on each row(as it describes [here](https://datasystemslab.github.io/GeoSpark/tutorial/rdd/#from-geojson)).
So basically you can take the output of the ogr2ogr, and remove the following section:
`{
"type": "FeatureCollection",
"name": "Trans_RoadSegment",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4269" } },
"features": [
`
and also the [{ at the end of the file

**Comment by SW186000** [comment]
You can load shapefiles by 3. because geospark uses hadoopNewAPI for loading.
>calling spatialRDD.analyze results in a null boundary envelope.
Please tell me how to reproduce the results.

**Comment by elfprince13** [comment]
> Please tell me how to reproduce the results.

3.

**Comment by SW186000** [comment]
@elfprince13 When I check the Trans_RoadSegment, it is Linestring so that it may be in a null boundary envelope.
