### ISSUE TITLE
The `Google Form` for feedback is no longer accepting responses

### ISSUE THREAD

**Issue by jbampton** [apache/sedona#762]
## Expected behavior

Form is still open for feedback.

## Actual behavior

"The form Feedback to Improve Apache Sedona is no longer accepting responses."

## Steps to reproduce the problem

On the website open the Google Form link:

https://sedona.apache.org/latest-snapshot/community/contact/#feedback

**Comment by jiayuasu** [comment]
Thanks! Will be fixing this soon.
