### ISSUE TITLE
st_geohash seems not working with southern hemisphere points

### ISSUE THREAD

**Issue by shenavaa** [apache/sedona#775]
## Expected behavior
spark-sql> select st_geohash(st_point(151.194,-33.816),3);
r3g
Time taken: 0.078 seconds, Fetched 1 row(s)
spark-sql>
## Actual behavior
spark-sql> select st_geohash(st_point(151.194,-33.816),3);
NULL
Time taken: 0.078 seconds, Fetched 1 row(s)
spark-sql>

## Steps to reproduce the problem
Launch a spark SQL shell with following command on EMR 6.9.0 and spark 3.3.0:

$ spark-sql --packages org.apache.sedona:sedona-python-adapter-3.0_2.12:1.2.0-incubating,org.apache.sedona:sedona-viz-3.0_2.12:1.2.0-incubating,org.datasyslab:geotools-wrapper:geotools-24.0   --conf spark.serializer=org.apache.spark.serializer.KryoSerializer   --conf spark.kryo.registrator=org.apache.sedona.viz.core.Serde.SedonaVizKryoRegistrator   --conf spark.sql.extensions=org.apache.sedona.viz.sql.SedonaVizExtensions,org.apache.sedona.sql.SedonaSqlExtensions

## Settings
All default. 1 single node EMR cluster, r6gd.2xlarge instance.

Sedona version = ?
1.2.0
Apache Spark version = ?
3.3.0
Apache Flink version = ?
NA
API type = Scala, Java, Python?
SQL
Scala version = 2.11, 2.12, 2.13?
2.12
JRE version = 1.8, 1.11?
[hadoop@ip-192-168-40-38 ~]$ java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment Corretto-8.352.08.1 (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM Corretto-8.352.08.1 (build 25.352-b08, mixed mode)

Python version = ?

Environment = Standalone, AWS EC2, EMR, Azure, Databricks?
EMR 6.9.0

**Comment by jiayuasu** [comment]
@shenavaa Does ST_GeoHash work for your other input in addition to southern hemisphere?

**Comment by Imbruced** [comment]
that is strange I am able to calculate geohash of point `151.194,-33.816` and I am getting `r3g` for precision of 3. Are you sure that geometry produced by constructor is not null ?
