### ISSUE TITLE
Is possible to use make_valid while using a constructor?

### ISSUE THREAD

**Issue by set92** [apache/sedona#782]
## Expected behavior

Read a file with incorrect geometries and not fail, or have some parameter to define if use make_valid while reading the file, or have some flag in case there are some errors while reading to assign it NULL or some value.

So, in the code I show below, I expected for the output to be like this:
```
+-----+------------------------+
|name |geometry                |
+-----+------------------------+
|good |POINT (4.66452 52.13046)|
|test1|NULL                    |
|test2|NULL                    |
+-----+------------------------+
```

## Actual behavior

Instead, I got a fail while reading the file with the error of the last row.

## Steps to reproduce the problem

This code has 2 mistakes, the second row is missing a ")", and the third one has an intersection.
```python
from pyspark.sql import SparkSession, Row
from pyspark.sql.types import StructType, StructField, StringType
import findspark
import pyspark

findspark.find()
findspark.init()
spark = SparkSession.builder \
                    .master('local[1]') \
                    .appName('test') \
                    .getOrCreate()

rows = [Row(geometry='POINT(4.66452 52.13046)', name='good'),
       Row(geometry='POINT(4.66452 52.13046', name='test1'),
       Row(geometry='POLYGON((0 -1, 2 1, 2 -1, 0 1))', name='test2')]
newDf = spark.sparkContext.parallelize(rows)
dfs2 = spark.createDataFrame(newDf, StructType([StructField('geometry', StringType(), True), StructField('name', StringType(), True)]))
dfs2.createOrReplaceTempView("location")

spark.sql(
      "SELECT name, st_geomFromWKT(geometry) as geometry from location"
).show(5)
```
## Settings

- Sedona version = 1.3.1
- Apache Spark version = 3.3.2
- API type = Python
- Scala version = 2.12
- JRE version = 1.8, 1.11?
- Python version = 3.9
- Environment = Standalone

**Comment by jiayuasu** [comment]
@umartin Marin I remember that you answered a similar question in Sedona Discord server but for RDD. I think an easy way to handle this in SQL is that we catch all exceptions in ST Constructors, return null and also print error message and stack trace. But is this the best practice?
