### ISSUE TITLE
Writing dataframe to Postgresql (Postgis-Extension) DB fails

### ISSUE THREAD

**Issue by conect** [apache/sedona#807]
## Expected behavior
Geojson is read and then written as dataframe to Postgresql DB

## Actual behavior
Following error occurs:
java.lang.IllegalArgumentException: Can't get JDBC type for array<tinyint>
	at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotGetJdbcTypeError(QueryExecutionErrors.scala:674)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$getJdbcType$2(JdbcUtils.scala:181)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getJdbcType(JdbcUtils.scala:181)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$savePartition$5(JdbcUtils.scala:705)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$savePartition$5$adapted(JdbcUtils.scala:705)
## Steps to reproduce the problem
```
SparkSession spark = SparkSession.builder()
                .master("local[*]") // Delete this if run in cluster mode
                .appName("readTestScala") // Change this to a proper name
// Enable Sedona custom Kryo serializer
                .config("spark.serializer", KryoSerializer.class.getName())
                .config("spark.kryo.registrator", SedonaKryoRegistrator.class.getName())
                .getOrCreate(); // org.apache.sedona.core.serde.SedonaKryoRegistrator
SedonaSQLRegistrator.registerAll(spark);
SedonaVizRegistrator.registerAll(spark);

SpatialRDD spatialRDD1 = GeoJsonReader.readToGeometryRDD(JavaSparkContext.fromSparkContext(spark.sparkContext()),"./src/main/resources/features.json",false,false);
 spatialRDD1.CRSTransform("epsg:4326","epsg:3857");
 Dataset<Row> d2 = Adapter.toDf(spatialRDD1,spark);
 d2.show();
 System.out.println(d2.schema());
 d2.write()
  .format("jdbc")
  .mode(SaveMode.Append )
  .option("url", "jdbc:postgresql://somedb")
  .option("dbtable", "sometable")
  .option("user", "someuser")
  .option("password", "somepw")
  .save();
```
## Settings

Sedona version = 
 <dependency>
            <groupId>org.apache.sedona</groupId>
            <artifactId>sedona-python-adapter-3.0_2.12</artifactId>
            <version>1.3.1-incubating</version>
        </dependency>
        <dependency>
            <groupId>org.apache.sedona</groupId>
            <artifactId>sedona-viz-3.0_2.12</artifactId>
            <version>1.3.1-incubating</version>
        </dependency>

Apache Spark version = 
  <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.12</artifactId>
            <version>3.2.1</version>
        </dependency>

Apache Flink version = ?

API type =  Java

JRE version = 1.8

Environment = Standalone

**Comment by umartin** [comment]
Hi @conect!

Postgis doesn't understand the Sedona internal serialization format. The native postgis protocol uses EWKB for geometries. Try converting the geometry with ST_AsEWKB before writing to postgis.

`Dataset<Row> d2 = Adapter.toDf(spatialRDD1,spark).withColumn("geometry", expr("ST_AsEWKB(geometry)"));`

Br,
Martin Andersson

**Comment by umartin** [comment]
Hi,

If you create the table externally to Spark before writing you can set the column type to geometry and Postgis will accept the EWKB as geometry. If you let Spark create the table you can change the column type post insert. Execute something like this in Postgis: "alter table my_table alter column geometry type geometry;".

Let me know if that works for you!

**Comment by conect** [comment]
Hi,

postgis doesn't seem to understand geometry, but when i use e.g. linegeometries: 
`alter table my_table alter column geometry type geometry(LineString,3857);`
than it works.

**Comment by conect** [comment]
Thank you this may be indeed be caused by the client (QGIS) that I used. Would have thought QGIS does understand this...
