### ISSUE TITLE
distance calculation is different in sedona(geometry) and postgis(geography)

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#829]
## Expected behavior
in sedona 
(geometry)point1 (geometry)point2 in srid 3857
st_distance( point1 ,point2)    get real distance in meters

in postgis
(geography)point1 (geography)point2 
st_distance( point1 ,point2)   get real distance in meters

## Actual behavior
the results are more and more different while coordinates goes to polar.

Is there a type in sedona like geography in postgis

## Settings

Sedona version = 1.4.0

Apache Spark version = 3.2.2

API type = Pure SQL & spark-shell

Scala version = 2.12

JRE version = 1.8

Environment = Ambari+apache community components

**Comment by jiayuasu** [comment]
We don't have the geography type support for now. One way to quickly fix this is to add the haversine distance calculator which will produce more similar results as PostGIS.

**Comment by MyqueWooMiddo** [comment]
> We don't have the geography type support for now. One way to quickly fix this is to add the haversine distance calculator which will produce more similar results as PostGIS.

Is this a good choice?
[https://gist.github.com/pavlov99/bd265be244f8a84e291e96c5656ceb5c](url)

**Comment by jiayuasu** [comment]
Thanks for the link. I don't have PostGIS in hand but can you confirm that the function provided in that post returns the same / similar result as PostGIS?

**Comment by jiayuasu** [comment]
Solved by PR #835

**Comment by MyqueWooMiddo** [comment]
> Thanks for the link. I don't have PostGIS in hand but can you confirm that the function provided in that post returns the same / similar result as PostGIS?
ST_DistanceSpheroid :  nearly the same result
ST_DistanceSphere  : difference in a dozen cm, quite near

**Comment by MyqueWooMiddo** [comment]
> Thanks for the link. I don't have PostGIS in hand but can you confirm that the function provided in that post returns the same / similar result as PostGIS?

ST_DistanceSpheroid : nearly the same result
ST_DistanceSphere : difference in a dozen cm, quite near
