### ISSUE TITLE
Is SpartialIndex available for multipolygon types ?

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#834]
Is SpartialIndex available for multipolygon types ?

**Comment by jiayuasu** [comment]
@MyqueWooMiddo Yes, SpatialIndex works for any geometry types in Sedona

**Comment by MyqueWooMiddo** [comment]
> @MyqueWooMiddo Yes, SpatialIndex works for any geometry types in Sedona

I see，THX
