### ISSUE TITLE
sedona/docs/image/geospark-zeppelin-demo.json not updated.

### ISSUE THREAD

**Issue by kartikeyhadiya** [apache/sedona#836]
## Expected behavior
In sedona/docs/image/geospark-zeppelin-demo.json, ST_PIXELIZE should be used with EXPLODE.

## Actual behavior
In sedona/docs/image/geospark-zeppelin-demo.json,  ST_PIXELIZE not used with EXPLODE which throws ST_PIXELIZE not a generator expression error.

## Steps to reproduce the problem
Execute all cells in sedona/docs/image/geospark-zeppelin-demo.json via zeppelin. 

Environment = [Spark-sedona-zeppelin docker image](https://hub.docker.com/r/kartikeyhadiya/sedona_zeppelin-0.10.1)

**Comment by kartikeyhadiya** [comment]
Thank you for merging. 
Can i add the docker image to Readme. Here is the github link for all the files [Github Link](https://github.com/kartikeyhadiya/sedona_zeppelin-0.10.1) and docker-hub link [Spark-sedona-zeppelin docker image](https://hub.docker.com/r/kartikeyhadiya/sedona_zeppelin-0.10.1)

**Comment by jiayuasu** [comment]
@kartikeyhadiya Thanks for proposing this. We usually don't put third-party docker images in our main repo as we cannot control the quality and security of the docker images. Do you want to merge your docker repo to Sedona repo?

To merge it, I suggest we add Jupyter notebook support as well, and also support the latest Sedona release 1.4.0

**Comment by kartikeyhadiya** [comment]
I would be happy to merge my docker repo to Sedona repo. Can you also host Sedona official image on the Docker hub?

I can work on adding Jupyter-Notebook support when I get time around this or next weekend.

Regarding support for Sedona release 1.4.0, I think Sedona is built upon Spark 3.2 or 3.3 but Zeppelin's latest version 0.10.1 only supports Spark 3.0.*. I initially tried Sedona 1.4.0 but I was facing issues executing example codes and upon googling I found those errors were due to spark version mismatch so, I fall back to 1.3.0 - incubating.

I think I can make a separate docker image for Sedona 1.4.0 with jupyter-notebook.

**Comment by jiayuasu** [comment]
Yes, we can host Sedona official docker image on DockerHub like here: https://hub.docker.com/u/apache , with approval of ASF (https://infra.apache.org/docker-hub-policy.html)

Thanks for your effort. Looking forward to it!

**Comment by kartikeyhadiya** [comment]
I will create a new issue for this for other contributor feedback as title doesn't match.
