### ISSUE TITLE
Update Conda Package

### ISSUE THREAD

**Issue by nullbutt** [apache/sedona#847]
## New Request

The current apache-sedona version available in conda is 1.3.1. Kindly requesting an update to 1.4.0

**Comment by jiayuasu** [comment]
@nullbutt The Conda package was not released by the Apache Sedona team. Is it released by this repo? https://github.com/conda-forge/apache-sedona-feedstock

**Comment by Kontinuation** [comment]
I've submitted https://github.com/conda-forge/apache-sedona-feedstock/pull/12 to adapt the conda build to apache-sedona 1.4.1. The reviewing process may take some time.

**Comment by nullbutt** [comment]
@Kontinuation many thanks!

**Comment by jiayuasu** [comment]
@Kontinuation @jmoraispk [apache-sedona-feedstock](https://github.com/conda-forge/apache-sedona-feedstock) has been left unattended for a very long time. This negatively affects our user experience. Is there a way that the Sedona team can take control and publish the packages ourselves?

**Comment by jmoraispk** [comment]
@jiayuasu I agree 100%. There is definitely a way: release pip packages. These can be updated directly by you in the pip repos and don't require conda revisions.

**Comment by jiayuasu** [comment]
@jmoraispk Do you mean this? https://pypi.org/project/apache-sedona/#history

We have been releasing Sedona to PyPi all the time.

**Comment by jmoraispk** [comment]
!!
Well, I apologize for my ignorance. Not sure how I missed this. Then, given that the installation via pip is available, I don't see why the UX would be influenced.

**Comment by jiayuasu** [comment]
Resolved. Sedona on Conda is up to date now == 1.5.0. See: https://github.com/conda-forge/apache-sedona-feedstock

**Comment by nullbutt** [comment]
many thanks @jiayuasu !
