### ISSUE TITLE
Spatial Joins with a Prebuilt Index Loads All Results In Memory

### ISSUE THREAD

**Issue by dfischercodethoughts** [apache/sedona#849]
## Expected behavior
Similar to the ```DynamicIndexLookupJudgement``` code, the prebuilt index ```Left/RightIndexLookupJudgement```s should operate on a new custom individual iterator which can ```loadNextBatch``` so an entire partition need not be read into executor memory.

## Actual behavior
The prebuilt index IntersectionJoinJudgement loads all results as a list in memory before returning an iterator.

## Steps to reproduce the problem
Create a geometry with 40k points and intersection join against 1m rows of medium/small geometries (~1kb each) with a prebuilt index. This will OOM on most default executors (i.e. ones with ~2-3 GB memory).

## Settings

**Comment by jiayuasu** [comment]
@dfischercodethoughts Thanks for catching this. Will fix this soon.

**Comment by jiayuasu** [comment]
Fixed by #851
