### ISSUE TITLE
Voronoi diagram / Thiessen polygons Feature

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#897]
Is there roadmap to support Voronoi diagram / Thiessen polygons Feature ?

**Comment by jiayuasu** [comment]
@MyqueWooMiddo Do you mean ST_VoronoiPolygons (https://postgis.net/docs/ST_VoronoiPolygons.html)?

**Comment by MyqueWooMiddo** [comment]
> @MyqueWooMiddo Do you mean ST_VoronoiPolygons (https://postgis.net/docs/ST_VoronoiPolygons.html)?

shide

**Comment by jiayuasu** [comment]
@MyqueWooMiddo Do you want to contribute this function to Sedona? JTS already has a voronoi diagram builder so implementing this shouldn't be hard: https://locationtech.github.io/jts/javadoc/org/locationtech/jts/triangulate/VoronoiDiagramBuilder.html

**Comment by alex-smith-ai** [comment]
Hello @MyqueWooMiddo and @jiayuasu. I would love to see the `VoronoiDiagramBuilder` mentioned above implemented and could help implement it. I'm experienced with spatial python, and am getting there with Sedona. Any suggestions on learning to contribute, specifically which API to start on? I've read the contributing guidelines, but am not sure on where to go from there.

**Comment by jiayuasu** [comment]
@MyqueWooMiddo @alex-smith-ai ST_VoronoiPolygon was just merged to the master branch: https://github.com/apache/sedona/pull/965

Is this what you want?

**Comment by alex-smith-ai** [comment]
@jiayuasu yes, that is exactly what I was looking for! Is this ready for production use cases?

**Comment by jiayuasu** [comment]
@alex-smith-ai Yes, it is. But we don't have an official release of it yet. It will be released in Sedona 1.5.0 which be out in late September. If you are interested in trying in out now, you can download the jar from our GitHub actions and use it together with Sedona Python SQL.

**Comment by alex-smith-ai** [comment]
@jiayuasu that is great news. Looking forward to trying it.
