### ISSUE TITLE
Alternative geojson reader/writer from jts-io

### ISSUE THREAD

**Issue by MyqueWooMiddo** [apache/sedona#900]
## Expected behavior
Alternative geojson reader/writer from jts-io ,  due to [jts2geojson](https://github.com/bjornharrtell/jts2geojson)  is not a famous lib.

**Comment by jiayuasu** [comment]
AFAIK, jts2geojson is the only library that handles GeoJSON Feature or FeatureCollection. JTS-IO only handles the `geometry` field of a geojson. Please correct me if I am wrong.
