### ISSUE TITLE
Bug in Raster Function RS_BandAsArray

### ISSUE THREAD

**Issue by kanchanchy** [apache/sedona#911]
## Expected behavior
I am trying to create a column with the raster function RS_BandAsArray to retrieve a specific band from the binary content. It should create the column with the corresponding band array.

## Actual behavior
Throws the following exception:
AnalysisException: cannot resolve 'rs_bandasarray(raster_df.content, 1)' due to data type mismatch: argument 1 requires raster type, however, 'raster_df.content' is of binary type.; line 1 pos 7;
'Project [rs_bandasarray(content#17, 1) AS data#43]
+- SubqueryAlias raster_df
   +- View (`raster_df`, [path#14,modificationTime#15,length#16L,content#17])
      +- Relation [path#14,modificationTime#15,length#16L,content#17] binaryFile

## Steps to reproduce the problem
raster_df = spark.read.format("binaryFile").load(PATH_TO_RASTER_IMAGES)
raster_df.createOrReplaceTempView("raster_df")
raster_df = spark.sql("select RS_BandAsArray(content, 1) as data from raster_df")
raster_df.show(5)

## Settings

Sedona version = 1.4.1

Apache Spark version = 3.4.1/3.3.2

Apache Flink version = ?
Not tested

API type = Scala, Java, Python?
Python

Scala version = 2.11, 2.12, 2.13?
2.12

JRE version = 1.8, 1.11?
1.11

Python version = ?
3.11.0

Environment = Standalone, AWS EC2, EMR, Azure, Databricks?
Standalone

**Comment by jiayuasu** [comment]
@kanchanchy You forgot to use RS_FromGeoTiff to process the binary format. See here: https://sedona.apache.org/1.4.1/api/sql/Raster-loader/

```
var df = spark.read.format("binaryFile").load("/some/path/*.tiff")
df = df.withColumn("raster", f.expr("RS_FromGeoTiff(content)"))
```

**Comment by kanchanchy** [comment]
Got it. I am closing the issue.
