### ISSUE TITLE
Support Uber H3 in Sedona?

### ISSUE THREAD

**Issue by MoSarwat** [apache/sedona#914]
## Settings

Sedona version = ?

Apache Spark version = ?

Apache Flink version = ?

API type = Scala, Java, Python?

Scala version = 2.11, 2.12, 2.13?

JRE version = 1.8, 1.11?

Python version = ?

Environment = Standalone, AWS EC2, EMR, Azure, Databricks?

**Comment by Imbruced** [comment]
@MoSarwat Can I pick this up ? We can use https://github.com/uber/h3-java as it is [Apache-2.0 license](https://github.com/uber/h3-java/blob/master/LICENSE). WDYT ?

**Comment by jiayuasu** [comment]
@Imbruced Hi Pawel, @zongsizhang has been working on several Sedona H3 functions for a while. He will commit a PR in the next few days. But there are more to do with those H3 functions and you are welcome to help with that 😁
