### ISSUE TITLE
Shpefile attributes do not produce values in the column after joining.

### ISSUE THREAD

**Issue by PrathameshDhapodkar** [apache/sedona#987]
## Expected behavior
value| current_timestamp | network_operator_name | dl_load_date | isDishNrCell | isSimDish | nrNci | AOI_ID | Cluster_ID
(nestedjsonvalue) | 8/22/2023 5:44:11 PM | Digicel | 8/22/2023 | FALSE | TRUE | 3569856325 | ALB | ALB-01-Downtown

## Actual behavior
value| current_timestamp | network_operator_name | dl_load_date | isDishNrCell | isSimDish | nrNci | AOI_ID | Cluster_ID
(nestedjsonvalue) | 8/22/2023 5:44:11 PM | Digicel | 8/22/2023 | FALSE | TRUE | 3569856325 |  | 

## Steps to reproduce the problem
actual dataframe is a streaming dataset running on spark cluster.

1. Create spark session
2. get shape file from location(s3 here)
code:
  def getAoiShapeDf: DataFrame  = {
    val aoiShapefileLocation = "s3://bucket/opensource_loc/top_shp/aoi_oto/"
    val aoiShapeRdd = ShapefileReader.readToGeometryRDD(session.sparkContext, aoiShapefileLocation)
    aoiShapeRdd.CRSTransform("epsg:4326", "epsg:5070", false)
    val aoiShapeDf = Adapter.toDf(aoiShapeRdd, session)
    aoiShapeDf
  }

  def getClusterShapeDf: DataFrame = {
    val clusterShapefileLocation = "s3://bucket/opensource_loc/top_shp/cluster_oto/"
    val clusterShapeRdd = ShapefileReader.readToGeometryRDD(session.sparkContext, clusterShapefileLocation)
    clusterShapeRdd.CRSTransform("epsg:4326", "epsg:5070", false)
    val clusterShapeDf = Adapter.toDf(clusterShapeRdd, session)
    clusterShapeDf
  }

3. join shape file dataframe with actual dataframe on ST_Contains join condition.
code:
  def enrichWithAoi(dataframe:DataFrame,clientLatColumn: String, clientLongColumn: String): DataFrame = {
    val networkAoiShape = broadcast(this.getAoiShapeDf.select("geometry","AOI_ID"))
    val ueDataWithGeom = dataframe.withColumn("aoiGeoPoint",
      expr(s"ST_TRANSFORM(ST_POINT(CAST($clientLatColumn AS DOUBLE), CAST($clientLongColumn AS DOUBLE)), 'EPSG:4326', 'EPSG:5070')"))
    val aoiShapeJoin = ueDataWithGeom.alias("roamingAoiData").join(networkAoiShape.alias("shapeData"),
      expr("ST_Contains(shapeData.geometry,roamingAoiData.aoiGeoPoint)"),"LeftOuter")
    aoiShapeJoin.drop("geometry","aoiGeoPoint")
  }

  def enrichWithCluster(dataframe: DataFrame, clientLatColumn: String, clientLongColumn: String): DataFrame = {
    val networkClusterShape = broadcast(this.getClusterShapeDf.select("geometry", "Cluster_ID"))
    val ueClusterDataWithGeom = dataframe.withColumn("clusterGeoPoint",
      expr(s"ST_TRANSFORM(ST_POINT(CAST($clientLatColumn AS DOUBLE), CAST($clientLongColumn AS DOUBLE)), 'EPSG:4326', 'EPSG:5070')"))
    val clusterShapeJoin = ueClusterDataWithGeom.alias("roamingClusterData").join(networkClusterShape.alias("shapeData"),
      expr("ST_Contains(shapeData.geometry,roamingClusterData.clusterGeoPoint)"), "LeftOuter")
    clusterShapeJoin.drop("geometry","clusterGeoPoint")
  }

I tried with schema for shape files as well. Still the same result.

## Settings
- EMR Serverless 6.9.0
- spark 3.3.2
- scala 2.12
- jdk 11

Sedona version = ?
implementation group: 'org.apache.sedona', name: 'sedona-python-adapter-3.0_2.12', version: '1.3.1-incubating'
implementation group: 'org.apache.sedona', name: 'sedona-viz-3.0_2.12', version: '1.4.1'
implementation group: 'org.apache.sedona', name: 'sedona-common', version: '1.4.1'
implementation group: 'org.apache.sedona', name: 'sedona-sql-3.0_2.12', version: '1.4.1'

Apache Spark version = ?
3.3.2

API type = Scala, Java, Python?
Scala

Scala version = 2.11, 2.12, 2.13?
2.12

JRE version = 1.8, 1.11?
jdk11

Environment = Standalone, AWS EC2, EMR, Azure, Databricks?
AWS EMR Serverless

**Comment by jiayuasu** [comment]
@PrathameshDhapodkar 

Are you sure your shapefile follows this structure and your path is `s3://mypath/myshapefile`

```
- shapefile1
- shapefile2
- myshapefile
    - myshapefile.shp
    - myshapefile.shx
    - myshapefile.dbf
    - myshapefile...
    - ...

```

**Comment by PrathameshDhapodkar** [comment]
Yes, it does, based on my last issue I changed my path to the folder where my shape file lies, instead of a specific shape file.

**Comment by jiayuasu** [comment]
@PrathameshDhapodkar Did you do `show()` on DFs produced in the second step? Does it print the actual schema? 

In addition, your jars are wrong. The three jars you need are 

```
<dependency>
  <groupId>org.apache.sedona</groupId>
  <artifactId>sedona-spark-shaded-3.0_2.12</artifactId>
  <version>1.4.1</version>
</dependency>
<dependency>
  <groupId>org.apache.sedona</groupId>
  <artifactId>sedona-viz-3.0_2.12</artifactId>
  <version>1.4.1</version>
</dependency>
<!-- Optional: https://mvnrepository.com/artifact/org.datasyslab/geotools-wrapper -->
<dependency>
    <groupId>org.datasyslab</groupId>
    <artifactId>geotools-wrapper</artifactId>
    <version>1.4.0-28.2</version>
</dependency>

```

**Comment by jiayuasu** [comment]
@PrathameshDhapodkar This is interesting. Would you mind share this shapefile with me?

**Comment by PrathameshDhapodkar** [comment]
Sure.
I'm trying to upload a shape file I'm working with Let me know if you could Download it.

[aoi.zip](https://github.com/apache/sedona/files/12528777/aoi.zip)

**Comment by PrathameshDhapodkar** [comment]
[dish_optoclusters.zip](https://github.com/apache/sedona/files/12528829/dish_optoclusters.zip)

**Comment by Kontinuation** [comment]
> 0 | [ 1 6 0 ... -75 65 64] | ABQ | Phoenix | PX | West
> 69 | [ 1 3 0 0 32 0 0 0 0 1 0 0 0 53

These outputs seems like geometries encoded as EWKB. The ones starting with `1 6 0` are multipolygons, and the ones starting with `1 3 0` are polygons.

The internal encoding of geometries in sedona-sql was not EWKB since 1.4.0. The appearance of EWKB encoded geometries may indicate that some earlier version of sedona was mixed into the environment. The gradle config you posted above shows that it was using `sedona-python-adapter-3.0_2.12:1.3.1-incubating`. Please make sure that these old dependencies were actually removed.

**Comment by PrathameshDhapodkar** [comment]
okay, now I changed my dependencies completely, I have-

    // https://mvnrepository.com/artifact/org.apache.sedona/sedona-viz-3.0
    implementation group: 'org.apache.sedona', name: 'sedona-viz-3.0_2.12', version: '1.4.1'
    // https://mvnrepository.com/artifact/org.apache.sedona/sedona-spark-shaded-3.0
    implementation 'org.apache.sedona:sedona-spark-shaded-3.0_2.12:1.4.1'
    // https://mvnrepository.com/artifact/org.datasyslab/geotools-wrapper
    implementation group: 'org.datasyslab', name: 'geotools-wrapper', version: '1.4.0-28.2'
    // https://mvnrepository.com/artifact/org.apache.sedona/sedona-python-adapter-3.0
    implementation group: 'org.apache.sedona', name: 'sedona-python-adapter-3.0_2.12', version: '1.4.1'
    
Code changes made:

class ShapeFilesProvider(session: SparkSession) {

STEP 1:
val sedona: SparkSession = SedonaContext.create(session)


STEP 2:
  def getAoiShapeDf: DataFrame  = {
    val aoiShapefileLocation = "s3://bucket/opensource_loc/top_shp/aoi_oto/"
    val aoiShapeRdd = ShapefileReader.readToGeometryRDD(session.sparkContext, aoiShapefileLocation)
    aoiShapeRdd.CRSTransform("epsg:4269", "epsg:5070", false)
    val aoiShapeDf = Adapter.toDf(aoiShapeRdd, session)
    aoiShapeDf
}


  def getClusterShapeDf: DataFrame = {
    val clusterShapefileLocation = "s3://ue-bronze-dish-wireless-source-data-np/opensource_loc/top_shp/cluster_oto/"
    val clusterShapeRdd = ShapefileReader.readToGeometryRDD(session.sparkContext, clusterShapefileLocation)
    clusterShapeRdd.CRSTransform("epsg:4269", "epsg:5070", false)
    val clusterShapeDf = Adapter.toDf(clusterShapeRdd, session)
    clusterShapeDf
}


STEP 3:
  def enrichWithAoi(dataframe:DataFrame,clientLatColumn: String, clientLongColumn: String): DataFrame = {
    val networkAoiShape = broadcast(this.getAoiShapeDf.select("geometry", "AOI_ID"))
    val ueDataWithGeom = dataframe.withColumn("aoiGeoPoint",
      expr(s"ST_Transform(ST_Point(CAST($clientLatColumn AS DOUBLE), CAST($clientLongColumn AS DOUBLE)), 'EPSG:4326', 'EPSG:5070')"))
    val aoiShapeJoin = ueDataWithGeom.alias("roamingAoiData").join(networkAoiShape.alias("shapeData"),
      expr("ST_Within(roamingAoiData.aoiGeoPoint, shapeData.geometry)"), "LeftOuter")
    aoiShapeJoin.drop("geometry","aoiGeoPoint")
  }

  def enrichWithCluster(dataframe: DataFrame, clientLatColumn: String, clientLongColumn: String): DataFrame = {
    val networkClusterShape = broadcast(this.getClusterShapeDf.select("geometry", "Cluster_ID"))
    val ueClusterDataWithGeom = dataframe.withColumn("clusterGeoPoint",
      expr(s"ST_Transform(ST_Point(CAST($clientLatColumn AS DOUBLE), CAST($clientLongColumn AS DOUBLE)), 'EPSG:4326', 'EPSG:5070')"))
    val clusterShapeJoin = ueClusterDataWithGeom.alias("roamingClusterData").join(networkClusterShape.alias("shapeData"),
      expr("ST_Within(roamingClusterData.clusterGeoPoint, shapeData.geometry)"), "LeftOuter")
    clusterShapeJoin.drop("geometry","clusterGeoPoint")
  }
  
  
OUTPUT for step 2:
aoiShapeDf = 

geometry | AOI_ID | Market | ...
b'b\x00\x00\x007\x01\x00\x00\xe7\xb44\xd6\x8cfoA1\x92\x1a\xdc\x0b#ZA\x17\xac\xb0\x10BfoA\xd6y\xdeC\xec\x1fZAb.\xdd\x04\x10foA\n\x1c_5a\x1eZA\xe9\x02\xc3\xab\xc4eoA\xfag\xe3\xa2\xdf\x1cZA\xdf\xcc\x8fo`eoA\x07\x11\xe8p\xc9\x19ZA$\x96\x19o\x15eoA\x82\x8c\x90\xf6\xa9\x16ZA{5\xd7@\xe3doA\x88\xbe\xc9\xfc\x1e\x15ZA7o\xe9\xb7\x97doA\xa5\xff\xe0\x8b\x9d\x13ZA\xc8\xa2\xa8 LdoA7\x9d>$\x1c\x12ZA5 V\x8d\xe7coA\x8c\x86\xe0\'\x06\x0fZA)\xa5!\xa6\xb5coA\x97\x0c\xc6C\xdd\x0bZA\x00\x07\xdc\xa9\x9ccoA\xf9\xf1\x08\xd3H\nZA\x94\x93\xa9\x99jcoA\x88\xe0\xc0\xca\x1f\x07ZA\x10\xa4>\xdbjcoAB\xa7\xaa\xcd\x81\x05ZA\xab\x00\xa2\x0ckcoA00\xc3\xd2\xe3\x03ZAT\x16\xf9\xecQcoAK\xde@fO\x02ZA\xcbS\xc6\x80\x1fcoA\xdf\x08X\x8a\xc4\x00ZA0h=\xc0\xd3boA"N\x11\x1aC\xffYA&IG\xc7nboA\xea\xdf\xa8w-\xfcYA\x1cJSA<boA\xad\xad\xfe\xab\xa2\xfaYA\xa3\xffj]\xf0aoA\x94\xe6\xa8\x80!\xf9YA\xbe1\x13\x01\xd7aoA\x0b\x1d\x10\x1f+\xf9YAL\\i2\xf0aoA\xecY\xf7\x80\xbf\xfaYA\x92\x05C\x80"boA\xa8\xd2\xc0H\xe8\xfdYA<\xe8\x19\x9f;boA\x04\xa2\xc0\xad|\xffYAN!\x1c7\x87boA\x19\xae\xca\t\x9c\x02ZA\xfe\xb9>\xb7\xd2boA5\x02\x15C\xbb\x05ZA<j\x1fN\xd2boA\xd9\xe4AGY\x07ZAW\x03L\xdd\xb8boA\x9d\r\xa5\xe1b\x07ZA\xbe\xf2\xb3\xee\x85boAN$H\x1bv\x07ZA>\x98\xefplboAw\xe4\x8a\xba\x7f\x07ZA(\x1b\xc4f\x85boA\x96N\x03O\x14\tZAA\x0e\xcf\xcb\x84boA\xd8x5Z\xb2\nZA\xe5\xa7\x96\xcb8boA\x9f\x93\xa251\tZA\xfe\x9c<\xba\xecaoA\xea1\xb5\xef\xaf\x07ZA<\xbb\x97"\xd3aoAJ|\xbc\x98\xb9\x07ZA\xcd\x10\xc3\n\xecaoA\x15\xfcu*N\tZA\x95aE`7boAw\xbdNTm\x0cZA\x9f\xcd\xcdM7boAQt>\xf4\x93\x0cZA\x94\xe7\xcen4boAsV\xa9e\x80\x0cZA\xe47MA1boA\xd5\x1e\xb2yk\x0cZA@\xf6a\x16.boAe\x9fkXW\x0cZA\x97\xd2\x97\xef*boA\x03\x94\xa0\x0bD\x0cZA 0x\xce\'boAy0\xbe\x9c1\x0cZA\xce\xd7\x89\xb4$boA\xb3.\xba\x14 \x0cZA\x9b\xe8 ?#boA.\xbb\\\x18\x18\x0cZA\xe5_I\xacLaoAEv\xcd\x98\x8e\x07ZA!\xeb\x98eUaoA5\xfdb\x82\xd3\nZA_\x02\xedk\xf2aoAm6A\x12%\x0eZA\x05^Y\x97\xe9aoA\xb8g\xbae(\x0eZA\xdc\x07Y\xe5\xcfaoAWTi\x132\x0eZA\xf90*\xef\xceaoA\xac\x0e\xe3+\xd0\x0fZA&\x0f \xa9\xe7aoA$\x9e\x04\x96d\x11ZA\x91P7\x1f\x1aboA\xc0\xd3\x14}\xef\x12ZA\xc47}\xf0~boAX\xe4\xc6\x01\x05\x16ZAV\xd1\xd2P\xb1boA6\x899\xc9\x8f\x17ZA-\xa7\xbdZ\xfdboA]P\xbf\xf0\x10\x19ZA\x1c<\xa9\xfdacoA]\xb8\xd5\xbf&\x1cZA\xdd\n\x12C\x94coA}\x16\xff\x97\xb1\x1dZA\x1f\xb1\xf3\'\xe0coAA\x07M\xd92\x1fZA\x07\x9f\x83\xfe+doA\xc0&\xea#\xb4 ZA\x14\xf8\x95\xc5wdoA\xcf\xbcJx5"ZA\x94`\x82\x7f\xc3doA\xce\xcd\x86\xd5\xb6#ZA\xe9\xfc\\\x0c\xdddoA\xd6\xdb@H\xad#ZA!\xfc\xb2\xf9\xdddoA\xd2X\xb0=\x0f"ZA\rU5\x9a)eoA\xc1\x87\xac\xa9\x90#ZA\xa4\x12\x9f\xb5[eoA\xff\x98o\xce\x1b%ZA\x13o\xd6?.... | ABQ | Phoenix | ...


I dont know why It gets converted to binary. I noitially it was array of numbers. 




OURPUT for step 3 remains the same the AOI_ID and Cluster_ID columns remain null.

**Comment by Kontinuation** [comment]
The binary representation of geometry seems to be OK. It is the internal representation of a MULTIPOLYGON in Sedona 1.4.1. It is also expected behavior to see geometry values being converted to binary. The SQL type of geometry values switched from ArrayData(ByteType) to BinaryType since https://github.com/apache/sedona/pull/734, so binary type is expected for 1.4.1.

AOI_ID and Cluster_ID in the joined dataframe could be null if there are no matching geometries in AOI or ClusterShape dataframe (since it is a left join). If points in dataframe do have overlapping geometries in AOI or ClusterShape, we may have to see if the broadcast-indexed left-join implementation in Sedona is correct.

I'm also curious about how you got the binary output. Directly calling `show` on the dataframe such as `getAoiShapeDf.show()` should give us WKT representation of geometries.

```
+--------------------+------+--------------+---------+---------+-----------------+-------+---------------+----------+-----------------+-----------------+-----------------+
|            geometry|AOI_ID|        Market|Market_ID|   Region|        Area_sqMi|  POP10|     AOI_gNodeB|Initial_gN|            POP20|       Shape_Leng|       Shape_Area|
+--------------------+------+--------------+---------+---------+-----------------+-------+---------------+----------+-----------------+-----------------+-----------------+
|MULTIPOLYGON (((-...|   ABQ|       Phoenix|       PX|     West|8.70397980649e+02| 914976|751000 - 751999|    751000|9.52772000000e+05|4.67168347352e+00|2.23052724795e-01|
|MULTIPOLYGON (((-...|   ABY|       Atlanta|       AT|    South|5.51813032030e+02| 208389|511000 - 511999|    511000|2.13365000000e+05|2.79135299123e+00|1.35288864354e-01|
|POLYGON ((-73.642...|   ALB|        Albany|       AL|Northeast|1.09007983321e+03| 806822|311000 - 311999|    311000|8.40656000000e+05|4.55576707507e+00|3.11131627244e-01|
...
```

**Comment by PrathameshDhapodkar** [comment]
Yes, that is correct. The shape file polygons were flipped from the source. The result works as expected now. Thank you so much for the help, really appreciate it.
